### ISSUE TITLE
it's don't work in b28 now

### ISSUE THREAD

**Issue by jjp9624022** [JacquesLucke/animation_nodes#1017]
File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\ui\mesh_indices.py", line 12, in drawIndicesOfSelectedObjects
    prefs = getMeshIndicesSettings()
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\preferences.py", line 206, in getMeshIndicesSettings
    return getPreferences().drawHandlers.meshIndices
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\preferences.py", line 191, in getPreferences
    return bpy.context.user_preferences.addons[addonName].preferences
AttributeError: 'Context' object has no attribute 'user_preferences'
Traceback (most recent call last):
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\ui\mesh_indices.py", line 12, in drawIndicesOfSelectedObjects
    prefs = getMeshIndicesSettings()
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\preferences.py", line 206, in getMeshIndicesSettings
    return getPreferences().drawHandlers.meshIndices
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\preferences.py", line 191, in getPreferences
    return bpy.context.user_preferences.addons[addonName].preferences
AttributeError: 'Context' object has no attribute 'user_preferences'
Traceback (most recent call last):
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\ui\mesh_indices.py", line 12, in drawIndicesOfSelectedObjects
    prefs = getMeshIndicesSettings()
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\preferences.py", line 206, in getMeshIndicesSettings
    return getPreferences().drawHandlers.meshIndices
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\preferences.py", line 191, in getPreferences
    return bpy.context.user_preferences.addons[addonName].preferences
AttributeError: 'Context' object has no attribute 'user_preferences'
Traceback (most recent call last):
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\ui\mesh_indices.py", line 12, in drawIndicesOfSelectedObjects
    prefs = getMeshIndicesSettings()
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\preferences.py", line 206, in getMeshIndicesSettings
    return getPreferences().drawHandlers.meshIndices
  File "C:\Users\jjp\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\preferences.py", line 191, in getPreferences
    return bpy.context.user_preferences.addons[addonName].preferences
AttributeError: 'Context' object has no attribute 'user_preferences'

**Comment by OmarSquircleArt** [comment]
Thanks for the report! This was already fixed, please wait for newer builds.
