### ISSUE TITLE
Impossible to bake sound (V.2.1.3)

### ISSUE THREAD

**Issue by softyoda** [JacquesLucke/animation_nodes#1035]
Hello, I'm having trouble bake the average or spectrum of a sound with blender animation node.

I have this error : `Traceback (most recent call last):
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\operators\dynamic_operators.py", line 52, in invoke_InvokeFunction
    return self.execute(context)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\operators\dynamic_operators.py", line 58, in execute_InvokeFunction
    self.an_executeCallback(self.callback, *args)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\extend_bpy_types.py", line 28, in _executeCallback
    executeCallback(callback, *args, **kwargs)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\operators\callbacks.py", line 25, in executeCallback
    callback(*parameters, args, kwargs)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\operators\callbacks.py", line 40, in executeNodeCallback
    getattr(node, functionName)(*args, **kwargs)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\nodes\sound\bake.py", line 158, in bakeAverageSound
    soundData = bake(sound, low, high, attack, release)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\nodes\sound\bake.py", line 317, in bake
    object = createObjectWithFCurveAsTarget()
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\utils\blender_ui.py", line 84, in wrapper
    output = function(*args, **kwargs)
  File "C:\Users\RYZEN\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\nodes\sound\bake.py", line 342, in createObjectWithFCurveAsTarget
    object.keyframe_insert(frame = 0, data_path = "location", index = 0)
AttributeError: 'NoneType' object has no attribute 'keyframe_insert'

location: <unknown location>:-1

`

Thank you for your support.

**Comment by OmarSquircleArt** [comment]
Thanks for the report, but the sound bake node was removed and replaced by another sound system. This should be available starting next build.

**Comment by softyoda** [comment]
I download the new version but i'm lost, is it still possible to do this example : https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/falloff/sound_falloff.html ? Thanks.

**Comment by OmarSquircleArt** [comment]
@softyoda Which example exactly?

**Comment by softyoda** [comment]
This one : https://animation-nodes-manual.readthedocs.io/en/latest/_images/sound_falloff_node_example1.png 

I don't know how to get sound falloff from sound of a sequence.

**Comment by OmarSquircleArt** [comment]
There is no longer a sound falloff. You may use the *Sound Spectrum* node instead.

**Comment by OmarSquircleArt** [comment]
Sound Falloff was removed but it may be added later, so until it is implemented, use the Sound Spectrum node.

**Comment by softyoda** [comment]
I tried to create this [example ](https://animation-nodes-manual.readthedocs.io/en/latest/_images/sound_falloff_node_example4.gif) again using the sound spectrum, but i did not find any solution to get sound falloff like in the GIF in the example.

![image](https://user-images.githubusercontent.com/13988751/55483671-5e75c300-5627-11e9-92bf-dffdd01a5d95.png)

**Comment by OmarSquircleArt** [comment]
@softyoda  The *Sound Falloff* node is getting added again in #1075. So perhaps you should wait for that patch to land.

**Comment by softyoda** [comment]
It's been 11 days you merged the sound falloff node, and i thank you, but since i can't compile a windows version (beceause of #1005 ), I asked friends to compile me for me, but I only found one person who managed to compile only the linux version.

Do you think it would be possible to have more animation node build, or a buildbot, or a special branch of blender for animation node ?

Thank you in advance for your support.

**Comment by OmarSquircleArt** [comment]
@softyoda I don't think we have the resources to do something like a buildbot. Chris has been making an up to date Windows Animation Nodes builds for some time, perhaps you should check his [website](https://prenninger.com/3d/). You may also ask him for it, I am sure he can provide one.
