### ISSUE TITLE
Possible Error in main_execution_unit.py AN-2.1

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1050]
I got this message in my terminal just now:

```
Traceback (most recent call last):
  File "/Users/mac/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/execution/main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 3, in <module>
ValueError: too many values to unpack (expected 2)
```

So I checked the file and this is the relevant function:

```python
    def executeUnit(self):
        try:
            exec(self.executeCodeObject, self.executionData, self.executionData)
            return True
        except:
            print("\n"*5)
            traceback.print_exc()
            ExceptionDuringExecution().report()
            return False
```
Line 38 is:

```python
exec(self.executeCodeObject, self.executionData, self.executionData)
```

This happens when I run my PyGame Initialisation node in 2.8, or 2.79 under AN 2.1, but it works with AN 2.0. Before I go changing this file, I thought I would check with you whether this is a problem with my PyGame INIT node:

```python
import bpy
from ... base_types import AnimationNode
from bpy.props import *
from ... events import propertyChanged
import pygame.midi

class MidiInitNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_MidiInitNode"
    bl_label = "MIDI RealTime Data"
    bl_width_default = 150

    message_e: StringProperty()
    pygame.midi.init()
    isPyGameInit: BoolProperty(name = "Pygame Output", default = True, update = propertyChanged)

    # Check number of devices and check they are MID Inputs, not Outputs
    mid1Valid = True
    MidiDevicesNbr = pygame.midi.get_count()
    if MidiDevicesNbr == 1:
        m_info1 = str(pygame.midi.get_device_info(0))
        message = 'Dev 1: ' + m_info1
        if m_info1.split(',')[2].strip() == '1':
            midiInput = pygame.midi.Input(0)
        else:
            # Reduce MidiDevicesNbr by 1 - this will now be 0 and trapped in the execute function
            MidiDevicesNbr = MidiDevicesNbr - 1
    elif MidiDevicesNbr == 2:
        m_info1 = str(pygame.midi.get_device_info(0))
        message = 'Dev 1: ' + m_info1
        m_info2 = str(pygame.midi.get_device_info(1))
        message1 = 'Dev 2: ' + m_info2
        if m_info1.split(',')[2].strip() == '1':
            midiInput = pygame.midi.Input(0)
        else:
            # Reduce MidiDevicesNbr by 1 and set midiInput 1 to invalid
            MidiDevicesNbr = MidiDevicesNbr - 1
            mid1Valid = False
        if m_info2.split(',')[2].strip() == '1':
            if mid1Valid: # Set second midiInput to this pygame input
                midiInput1 = pygame.midi.Input(1)
            else: # Set first midiInput to this pygame input (only this is valid)
                midiInput = pygame.midi.Input(1)
        else:
            # Reduce MidiDevicesNbr by 1
            MidiDevicesNbr = MidiDevicesNbr - 1
    else:
        # We only handle up to 2 interfaces for now
        message = 'None or More than 2, MIDI Interface(s)'
        # By now we should have a number for valid Midi Inputs
        # If both were Ouputs, we have none, this is trapped in the execute function.

    def create(self):
        # New Input to set number of packets to read:
        self.newInput("Integer", "MIDI Packets To Read", "num_p")
        self.newOutput("Vector List", "MIDI Buffer", "m_buff")
        if self.MidiDevicesNbr == 2:
            self.newOutput("Vector List", "MIDI Buffer 2", "m_buff2")
        self.newOutput("Integer", "MIDI Device Count", "m_num")

    def draw(self,layout):
        col = layout.column()
        col.scale_y = 1.5
        layout.prop(self, "isPyGameInit")
        if self.message != '':
            layout.label(text=self.message, icon = "INFO")
        if self.MidiDevicesNbr == 2:
            if self.message1 != '':
                layout.label(text=self.message1, icon = "INFO")
        if self.message_e != '':
            layout.label(text=self.message_e, icon = "CANCEL")
        self.invokeFunction(col, "quitMidi", icon = "CANCEL",
            text = "Stop MIDI Feed")

    def execute(self, num_p):
        self.use_custom_color = True
        self.useNetworkColor = False
        self.color = (1,1,0.75)
        if self.MidiDevicesNbr == 0 or self.MidiDevicesNbr > 2:
             return [],[],self.MidiDevicesNbr
        buffer = []
        if self.MidiDevicesNbr == 2:
            buffer2 = []
        # Check Num Packets is greater than 0
        if num_p < 1:
            self.message_e = 'Set MIDI Packets!'
            if self.MidiDevicesNbr == 1:
                return [], self.MidiDevicesNbr
            elif self.MidiDevicesNbr == 2:
                return [], [], self.MidiDevicesNbr
        else:
            self.message_e = ''

        if self.isPyGameInit and pygame.midi.Input.poll(self.midiInput):
        # messages are formatted this way: [[message type, note / parameter ID, velocity / parameter value, ?], TimeStamp]
            buffer = pygame.midi.Input.read(self.midiInput, num_p)
        # Read second midi input
        if self.MidiDevicesNbr == 2:
            buffer2 = pygame.midi.Input.read(self.midiInput2, num_p)
        # Return for 1 input
        if self.MidiDevicesNbr == 1:
            return buffer, self.MidiDevicesNbr
        # Return for 2 inputs
        elif self.MidiDevicesNbr == 2:
            return buffer, buffer2, self.MidiDevicesNbr
        else:
            # Return for no, or more than 2 inputs
            return [], [], self.MidiDevicesNbr

    def quitMidi(self):
        if self.isPyGameInit:
            self.midiInput.close()
            # Close second input
            if self.MidiDevicesNbr == 2:
                self.midiInput2.close()
            #pygame.midi.quit() This causes error and is actioned by quiting Blender, I think...
            self.isPyGameInit = False
            self.message_e = 'Restart Blender to Restart MIDI Feed'

```

Which works perfectly well in AN 2.0 (apart from the annotations, obviously). Could you confirm whether my node is not right for AN2.1, or whether there is a little bug somewhere in main_execution_unit.py at line 38.

Thanks, Clock.

**Comment by JacquesLucke** [comment]
You probably return the wrong number of values from your `execute` method.

Maybe it helps when you change the code generation to "Monitored" in the developer panel. (haven't tried that in a long time)

**Comment by Clockmender** [comment]
Thanks, let me try that...

**Comment by Clockmender** [comment]
Aha, yes it is me being stupid....

This section is executed when I have 0, or more than 2, MIDI input devices:

```python
if self.MidiDevicesNbr == 0 or self.MidiDevicesNbr > 2:
             return [],[],self.MidiDevicesNbr
```

And the number fo outputs is 2 in this condition, not 3 - Oh dear.....

I changed it to `return [],self.MidiDevicesNbr` and all is well.

I don't think I ever checked this with no MIDI device attached, so that's what went wrong here. Thank you!
