### ISSUE TITLE
"Create Spline List" crashes animation nodes in 2.80

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#1057]
Just create a new scene, create a "Create Spline List", try to add a spline to the list and I get this error:

`Traceback (most recent call last):
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/execution/main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'FallCubes'", line 9, in <module>
NameError: name '_subprogram_zdvii29uimhpc5r' is not defined
Traceback (most recent call last):
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/utils/handlers.py", line 44, in always
    handler()
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/events.py", line 36, in sceneUpdated
    evaluateRaisedEvents()
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/events.py", line 44, in evaluateRaisedEvents
    event_handler.update(event.getActives())
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/utils/recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/event_handler.py", line 23, in update
    executeNodeTrees(nodeTrees)
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/execution/auto_execution.py", line 15, in executeNodeTrees
    nodeTree.autoExecute()
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/base_types/node_tree.py", line 86, in autoExecute
    self._execute()
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/base_types/node_tree.py", line 104, in _execute
    success = unit.execute()
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/execution/main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes.problems.ExecutionUnitNotSetup
`

**Comment by juangea** [comment]
Ok, I detected that this happens when the spline type is not bezier, when they are poly, so instead of launching this exception it could launch a warning and avoid adding that object I assume.

Cheers!

**Comment by OmarSquircleArt** [comment]
I can't replicate this error. I have the following node tree:

![Node Tree](https://user-images.githubusercontent.com/25300994/54807579-53fe1580-4c86-11e9-8245-7f78d009a080.png)

Can you share your exact setup?

**Comment by juangea** [comment]
Do it simpler.

Try this way:

1.- Create a box and add a bevel
2.- Extract some edges as two or three curves (each curve with various segments) 
3.- create a "Create Spline List" node
4.- Add those extracted curves to the list

It should crash, I just testet that workflow and it crashes.

![image](https://user-images.githubusercontent.com/20524718/54863720-5b87f200-4d4c-11e9-9203-1c84423f3ed6.png)

**Comment by OmarSquircleArt** [comment]
Thanks for the report! Fixed in 3be1495.
