### ISSUE TITLE
External Script Fails - Calling bpy.context

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1058]
This script works in Blender 2.8 (AN 2.1):

```python
import bpy

col = bpy.context.collection
inpM = col.objects['Test_Cube']
outM = col.objects['Test_Cube-2']
inpM.select_set(state=True)
outM.select_set(state=True)
ctx = bpy.context.copy()
ctx['active_object'] = outM
ctx['selected_objects'] = [inpM,outM]
bpy.ops.object.join(ctx)
```

But this function in an external script file:

```python
import bpy

def joinObjects(col,joinTo,toJoin):
    joinTo.select_set(state=True)
    toJoin.select_set(state=True)
    ctx = bpy.context.copy()
    ctx['active_object'] = joinTo
    ctx['selected_objects'] = [joinTo,toJoin]
    bpy.ops.object.join(ctx)
    return
```

Gives this error:

```
Traceback (most recent call last):
  File "/Users/mac/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/execution/main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 6, in <module>
  File "/Users/mac/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/nodes/clock/solver_three.py", line 42, in execute
    joinObjects(col,ob1,ob2)
  File "/Users/mac/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/nodes/clock/util_functions.py", line 9, in joinObjects
    bpy.ops.object.join(ctx)
  File "/Users/mac/Documents/Blender/2.8-files/software/blender-2.80.0-git20190308.5af85d904e5b-x86_64/blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py", line 198, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Operator bpy.ops.object.join.poll() failed, context is incorrect
Info: Saved "solver-prop.blend"
```

Here is the node code:

```python
import bpy
from bpy.props import *
from ... base_types import AnimationNode
from ... events import propertyChanged
from mathutils import Vector, Euler
from . util_functions import joinObjects

variables = {}

class an_SolverThreeNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_SolverThreeNode"
    bl_label = "SOLVER Propagate"
    bl_width_default = 220

    useScl: BoolProperty(name='Scale Loc Delta',default = False,update=propertyChanged)
    startF: IntProperty(name="Start Frame",default=2,min=2,update=propertyChanged)
    stopF:  IntProperty(name="Stop Frame",default=3,min=3,update=propertyChanged)
    lastF:  IntProperty(name="Last Frame",default=3,min=3,update=propertyChanged)

    def draw(self,layout):
        layout.prop(self,"startF")
        layout.prop(self,"stopF")
        layout.prop(self,"useScl")

    def create(self):
        self.newInput("an_ObjectSocket","Input Mesh","inpM")
        self.newInput("an_ObjectSocket","Output Mesh","outM")
        self.newInput("an_MatrixSocket","Location Delta","matrix")

    def execute(self,inpM,outM,matrix):
        variables['Matrix'] = matrix                    # Write int Matrix into variables dictionary
        col = bpy.context.collection
        frameC = bpy.context.scene.frame_current
        if inpM is not None and outM is not None:
            if frameC == self.startF:
                self.lastF = frameC
                dataN=inpM.data.copy()
                outM.data = dataN                       # Copy Input's data to Output Mesh
            elif frameC == self.startF + 1:
                ob1 = col.objects['Test_Cube']
                ob2 = col.objects['Test_Cube-2']
                joinObjects(col,ob1,ob2)
```

And the project:

![Screen Shot 2019-03-22 at 11 34 46](https://user-images.githubusercontent.com/29657804/54817167-274dfc00-4c8e-11e9-9580-ea4cd5ae5c4f.png)

Why is this so? What must I do to be able to join two objects from a Node?

**Comment by OmarSquircleArt** [comment]
The `object.join` operator requires a certain context to execute in, its `poll` function runs before the operator executes to make sure the context is correct. In your case the `poll` failed, so the context must be incorrect.

When you created a copy of the context, the area was probably something like `NODE_EDITOR`, while the operator needs the area type to be `VIEW_3D`. So you need to overwrite this as well, [this section](https://docs.blender.org/api/blender2.8/bpy.ops.html#execution-context) of the documentation explains this with an example.

Generally, however, you should avoid using operators when making nodes.

**Comment by Clockmender** [comment]
Thank you for the reply. I came to the same conclusion that using ops in nodes is not a good idea about 2 hours after I posted the thread!

So now I am cloning the geometry from the second object, transforming it as required, then appending it to the first object. This works very well. Also having great fun with matrices, Blender does matrices so unlike my previous work with matrix algebra in finite element analysis....

**Comment by Clockmender** [comment]
Hello @OmarSquircleArt all is well with my method now and all works nicely:

![Screen Shot 2019-03-23 at 13 13 30](https://user-images.githubusercontent.com/29657804/54865913-2e940900-4d65-11e9-9147-3c967c8b37b2.png)

This node generates "trail" geometry based upon an input object and a Matrix of transforms.

Thanks and good luck with your exams... I remember Uni exams from 40 odd years ago!
