### ISSUE TITLE
Cannot enable Animation Nodes, build 2.8 from day "25/03/19)

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#1061]
Yesterday I was able to have it enabled and work with it, the only problem was the rendering bug, but today I cannot even enable it, here is the information shown in the Info panel:

Traceback (most recent call last):
  File "/home/jgea/blender-git/build_master/bin/2.80/scripts/modules/addon_utils.py", line 384, in enable
    mod.register()
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/__init__.py", line 172, in register
    auto_load.register()
  File "/home/jgea/.config/blender/2.80/scripts/addons/animation_nodes/auto_load.py", line 28, in register
    bpy.utils.register_class(cls)
RuntimeError: Error: 'an_number_menu' doesn't contain '_MT_' with prefix & suffix

Help is VERY welcome please, even if I have to modify the addon manually.

**Comment by OmarSquircleArt** [comment]
Thanks for the report! It seems they started enforcing class naming conventions. This will probably require a lot of code updating. I will start updating on thursday as I have exams now. Meanwhile, use an older blender build.

**Comment by OmarSquircleArt** [comment]
Fixed in fd4599e.
