### ISSUE TITLE
Fatal error - AN v2.1.4 py3.7 Windows x64 / Blender 2.8 build in the description

### ISSUE THREAD

**Issue by prubini87** [JacquesLucke/animation_nodes#1069]
Blender build: blender-2.80.0-git.adfdae3fc2f4-windows64

I was unable to install Animation Nodes 2.1.4 and the console says:

`Read prefs: C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\blender-2.80.0-git.adfdae3fc2f4-windows64\2.80\python
Traceback (most recent call last):
  File "C:\blender-2.80.0-git.adfdae3fc2f4-windows64\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'animation_nodes'
addon_utils.disable: animation_nodes not disabled
Modules Installed (animation_nodes) from 'C:\\Users\\Pedro\\Downloads\\animation_nodes_v2_1_4_windows_py37.zip' into 'C:\\Users\\Pedro\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Exception in module register(): C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py
Traceback (most recent call last):
  File "C:\blender-2.80.0-git.adfdae3fc2f4-windows64\2.80\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py", line 172, in register
    auto_load.register()
  File "C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\auto_load.py", line 28, in register
    bpy.utils.register_class(cls)
RuntimeError: Error: 'an_id_keys_panel' doesn't contain '_PT_' with prefix & suffix`

Has anybody else run into that?

**Comment by OmarSquircleArt** [comment]
Thanks for the report! This was fixed yesterday in fd4599e.
I believe the latest blender build from the build bot will run Animation Nodes with no problems.

**Comment by prubini87** [comment]
Thank you so much for your prompt answer @OmarSquircleArt !

I've just compiled the blender 2.8 branch and testing it on the latest blender 2.8 release, it's yielding this error now:

`Read prefs: C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\blender-2.80.0-git.99d4321feff6-windows64\2.80\python
Traceback (most recent call last):
  File "C:\blender-2.80.0-git.99d4321feff6-windows64\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py", line 155, in <module>
    modules = import_modules.importAllSubmodules(__path__[0], __package__)
  File "C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\import_modules.py", line 8, in importAllSubmodules
    module = importlib.import_module("." + name, packageName)
  File "C:\blender-2.80.0-git.99d4321feff6-windows64\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "animation_nodes\graphics\c_utils.pyx", line 6, in init animation_nodes.graphics.c_utils
NameError: name 'glVertex3f' is not defined
addon_utils.disable: animation_nodes not disabled
Traceback (most recent call last):
  File "C:\blender-2.80.0-git.99d4321feff6-windows64\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py", line 155, in <module>
    modules = import_modules.importAllSubmodules(__path__[0], __package__)
  File "C:\Users\Pedro\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\import_modules.py", line 8, in importAllSubmodules
    module = importlib.import_module("." + name, packageName)
  File "C:\blender-2.80.0-git.99d4321feff6-windows64\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "animation_nodes\graphics\c_utils.pyx", line 6, in init animation_nodes.graphics.c_utils
NameError: name 'glVertex3f' is not defined`

Do you have any ideas on how to fix that?

Is Blender 2.8 the branch I must use or 2.1? Which is more up to date, please?

**Comment by prubini87** [comment]
Ok, confirming [v2.1.4 test builds for Blender 2.8](https://github.com/JacquesLucke/animation_nodes/releases) is working fine in latest Blender 2.8 build.

**Comment by OmarSquircleArt** [comment]
The Blender2.8 is the most up to date branch.
It seems this error is the result of left-over files from a previous Animation Nodes installation. Sometimes you will have to remove the addon completely and execute `python setup.py clean` for it to compile and work correctly.
