### ISSUE TITLE
Bug with color input from the material output node

### ISSUE THREAD

**Issue by picpic1979** [JacquesLucke/animation_nodes#1087]
Traceback (most recent call last):
  File "C:\Users\apicq\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 7, in <module>
  File "C:\Users\apicq\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\nodes\material\material_output.py", line 44, in setAttribute_Color
    setattr(material, attribute, newColor)
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3

Hi, i tried to set a material output for an object and the addon tell to me that color input take 4 input and not 3 

[https://photos.app.goo.gl/noKRnuprETXnQuwP8](url)
this is my setup

thanks

**Comment by OmarSquircleArt** [comment]
Thanks for the report! This was already fixed in 6500e941342acecc46f38e0eb743610500672e91.

**Comment by picpic1979** [comment]
sorry for that where can i find the latest build i have the 2.1.4.

Thanks

**Comment by OmarSquircleArt** [comment]
There are no official builds with this bug fix yet. You will have to wait until builds are available or try and compile AN yourself.
