### ISSUE TITLE
blender wont let me enable the addon. Trace back error

### ISSUE THREAD

**Issue by conquerorcode** [JacquesLucke/animation_nodes#1092]
This is the error message i got

Traceback (most recent call last):
  File "/private/var/folders/r5/949bmg0904x805qsymtpzfqm0000gn/T/AppTranslocation/9B4E042F-CACA-49F6-B74B-C343D97D1654/d/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 384, in enable
    mod.register()
  File "/Users/vijaypande/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/__init__.py", line 172, in register
    auto_load.register()
  File "/Users/vijaypande/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/auto_load.py", line 28, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass

**Comment by OmarSquircleArt** [comment]
I can't replicate this on latest Blender and latest AN versions. Can you try with the latest nighty build and latest AN build?

**Comment by conquerorcode** [comment]
I'm sorry but what is nightly
