### ISSUE TITLE
Sound Spectrum node broken

### ISSUE THREAD

**Issue by dimasddim** [JacquesLucke/animation_nodes#1122]
Unable to load a sound file in daily build (11.06.2019 - a0608340ae14).

I'm using this AN build from:
https://blender.community/c/graphicall/wdbbbc/

![image](https://user-images.githubusercontent.com/20833397/59253643-e21be380-8c58-11e9-87d3-ccd3d06092e8.png)

this is the log:
```
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\operators\path_chooser.py", line 16, in execute
    self.an_executeCallback(self.callback, self.filepath)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\extend_bpy_types.py", line 29, in _executeCallback
    executeCallback(callback, *args, **kwargs)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\operators\callbacks.py", line 25, in executeCallback
    callback(*parameters, args, kwargs)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\operators\callbacks.py", line 48, in executeSocketCallback
    getattr(socket, functionName)(*args, **kwargs)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\sockets\sound.py", line 59, in loadSound
    frame_start = bpy.context.scene.frame_start)
RuntimeError: Error: Sequences.new_sound: unable to open sound file


location: <unknown location>:-1
```

**Comment by OmarSquircleArt** [comment]
I can replicate this, thanks for the report!

**Comment by OmarSquircleArt** [comment]
Can you try the latest Blender 2.8 build and tell me if the issue still occur?

**Comment by OmarEmaraDev** [comment]
@dimasddim Can you report back on this?
