### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by insertcoindottv** [JacquesLucke/animation_nodes#1219]
Hi guys, i'm trying to install AN 2.1.5 but i got this errors:

addon_utils.disable: animation_nodes not disabled
Modules Installed (animation_nodes) from 'P:\\_iNSTALLERs_\\_Blender\\2.8_addons e varie\\animation_nodes_v2_1_windows_py37.zip' into 'C:\\Users\\mmone\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\mmone\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\mmone\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\mmone\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\mmone\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\mmone\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\libs\FastNoiseSIMD\__init__.py", line 1, in <module>
    from . node_base import Noise3DNodeBase
  File "C:\Users\mmone\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\libs\FastNoiseSIMD\node_base.py", line 6, in <module>
    from . wrapper import (
ImportError: DLL load failed: The specified module could not be found.

Any ideas?
Thanks in advance.

Max.

**Comment by charleshetier** [comment]
The @insertcoindottv solution worked for me. 
Downloaded from here: https://support.microsoft.com/fr-fr/help/2977003/the-latest-supported-visual-c-downloads

As a particularity maybe, I have VS2019 installed on my laptop, could it be a clue?
