### ISSUE TITLE
Sound From Sequence crash everytime is blender file is saved

### ISSUE THREAD

**Issue by Gianni-B** [JacquesLucke/animation_nodes#1221]
Hi,
I'm trying to use Sound from Sequence for a project. All works fine until i save the blend file, after that the node tree crash everytime i try to play the song. I've tried to change the sound file several times but doesn't work.
This is the Report from the Animation node Console

Traceback (most recent call last):
  File "C:\Users\Gianni\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Music stream'", line 3, in <module>
  File "C:\Users\Gianni\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\nodes\sound\sound_from_sequence.py", line 19, in execute
    return Sound([SoundSequence.fromSequence(s) for s in sequences if s is not None and s.type == "SOUND"])
  File "C:\Users\Gianni\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\nodes\sound\sound_from_sequence.py", line 19, in <listcomp>
    return Sound([SoundSequence.fromSequence(s) for s in sequences if s is not None and s.type == "SOUND"])
  File "C:\Users\Gianni\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 26, in fromSequence
    soundData = getCachedSoundDataFromSound(sequence.sound)
  File "C:\Users\Gianni\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 39, in getCachedSoundDataFromSound
    return getSoundData(sound.factory)
  File "C:\Users\Gianni\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 42, in getSoundData
    if sound.specs[0] == sampleRate:
AttributeError: 'NoneType' object has no attribute 'specs'

**Comment by OmarEmaraDev** [comment]
I think we solved that bug already, can you update to the latest version and try again?

**Comment by Gianni-B** [comment]
ok i have installed vc_redist.x64 and the last version worked fine. Thanks, and sorry for the inconvinience.
