### ISSUE TITLE
AnimationNodes Load DLL Failed

### ISSUE THREAD

**Issue by Ritsuka912** [JacquesLucke/animation_nodes#1222]
Traceback (most recent call last):
  File "D:\Toolkit\blender-2.80-windows64\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Tei\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\Tei\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\Tei\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\Tei\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "D:\Toolkit\blender-2.80-windows64\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Tei\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\libs\FastNoiseSIMD\__init__.py", line 1, in <module>
    from . node_base import Noise3DNodeBase
  File "C:\Users\Tei\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\libs\FastNoiseSIMD\node_base.py", line 6, in <module>
    from . wrapper import (
ImportError: DLL load failed: 指定されたモジュールが見つかりません。

**Comment by OmarEmaraDev** [comment]
Install `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).

**Comment by OmarEmaraDev** [comment]
Did this resolve your issue?

**Comment by Gerstmann-Bradley** [comment]
> Did this resolve your issue?

Not the original poster, but I had same issue installing new 2.1.5, and my friend had this issue for 2.1.4. Both of us solved this problem using your method. Thanks a lot.
