### ISSUE TITLE
Sound Spectrum Red Box Crash

### ISSUE THREAD

**Issue by tcohantz** [JacquesLucke/animation_nodes#1233]
Blender: v2.80.75
Animation Nodes: v2.1.5

I have been experiencing a reoccurring bug whenever I use the sound spectrum nodes. Usually a simple change to the node tree (such as simply adding in a node, without connecting it, or changing a value) will cause animation nodes to crash. Once the red box appears, there is no way to revive animation nodes, even an entire delete/removal of the node tree wont solve the issue. Reloading the file also wont solve the problem, and the red box persists. I am using .wav audio files.

I am copying the console log, though not sure if it will be useful as I closed the initial file and reopened it.
Traceback (most recent call last):
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\units.py", line 58, in setupExecutionUnits
    unit.setup()
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 26, in setup
    exec(self.setupCodeObject, self.executionData, self.executionData)
  File "setup: 'NodeTree.001'", line 13, in <module>
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\sockets\sound.py", line 42, in getValue
    soundSequence = SoundSequence.fromSequence(sequence)
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 26, in fromSequence
    soundData = getCachedSoundDataFromSound(sequence.sound)
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 39, in getCachedSoundDataFromSound
    return getSoundData(sound.factory)
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 42, in getSoundData
    if sound.specs[0] == sampleRate:
AttributeError: 'NoneType' object has no attribute 'specs'
Traceback (most recent call last):
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\utils\handlers.py", line 44, in always
    handler()
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\events.py", line 36, in sceneUpdated
    evaluateRaisedEvents()
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\events.py", line 44, in evaluateRaisedEvents
    event_handler.update(event.getActives())
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\utils\recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\event_handler.py", line 23, in update
    executeNodeTrees(nodeTrees)
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\auto_execution.py", line 15, in executeNodeTrees
    nodeTree.autoExecute()
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\base_types\node_tree.py", line 87, in autoExecute
    self._execute()
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\base_types\node_tree.py", line 105, in _execute
    success = unit.execute()
  File "C:\Users\tcoha\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes.problems.ExecutionUnitNotSetup

**Comment by OmarEmaraDev** [comment]
We fixed a similar bug a while ago, can you try the latest build of Animation Nodes?

**Comment by tcohantz** [comment]
Thanks! I will. Hate to be another person complaining about installation issues.... but, Im havin a problem. I downloaded the latest Window build from graphicall (Singhs extra nodes). Deleted all prior folders, etc. and installed the zip. When I click to activate, I get the following error message. Kinda confused how to resolve it.
![anim_error](https://user-images.githubusercontent.com/20898116/68913000-73553000-078c-11ea-9d7e-684d13ab1150.jpg)

**Comment by OmarEmaraDev** [comment]
Install `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).

**Comment by tcohantz** [comment]
That did it! Thank you so much for the help and prompt reply, I really
appreciate it :)
