### ISSUE TITLE
Cannot install Animation Nodes In 2.81 

### ISSUE THREAD

**Issue by DaitomodachiChannel** [JacquesLucke/animation_nodes#1244]
Hi there! I tried installing the animation nodes addon for 2.81, but I keep getting the following error.

https://cdn.discordapp.com/attachments/207019813069914113/649258198313730060/unknown.png

Traceback (most recent call last):                                                                                                                                                                                     File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 351, in enable                                                                                                       mod = __import__(module_name)                                                                                                                                                                                      File "C:\Users\daito\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\animation_nodes\__init__.py", line 166, in <module>                                                                                auto_load.init()                                                                                                                                                                                                   File "C:\Users\daito\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\animation_nodes\auto_load.py", line 23, in init                                                                                    modules = get_all_submodules(Path(__file__).parent)                                                                                                                                                                File "C:\Users\daito\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules                                                                      return list(iter_submodules(directory, directory.name))                                                                                                                                                            File "C:\Users\daito\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules                                                                         yield importlib.import_module("." + name, package_name)                                                                                                                                                            File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\importlib\__init__.py", line 127, in import_module                                                                                              return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                        File "C:\Users\daito\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\animation_nodes\libs\FastNoiseSIMD\__init__.py", line 1, in <module>                                                               from . node_base import Noise3DNodeBase                                                                                                                                                                            File "C:\Users\daito\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\animation_nodes\libs\FastNoiseSIMD\node_base.py", line 6, in <module>                                                              from . wrapper import (                                                                                                                                                                                          ImportError: DLL load failed: The specified module could not be found.

**Comment by OmarEmaraDev** [comment]
See #1240.
