### ISSUE TITLE
texture node

### ISSUE THREAD

**Issue by Yerus** [JacquesLucke/animation_nodes#1245]
Hi! I have an error when I use the texture node from AN 2.1.4.
I'm trying to apply a texture to a cube in standard way like in the video https://www.youtube.com/watch?v=0ot1CCy-MOg

And I also wanted to ask, if I may, can I only apply parts of a texture upon a mesh? Like setting not all the mesh vertices to the texture. And can I apply a texture to a 3d mesh, because in the video is only applied to a flat obj. My e-mail:
gsfinardi@hotmail.com

Traceback (most recent call last):
  File "C:\Users\Yerus\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 41, in <module>
  File "C:\Users\Yerus\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\nodes\newnodes\set_vertex_colors.py", line 62, in executeColors
    colorLayer.data.foreach_set("color", colorsList(self, colors))
RuntimeError: internal error setting the array

**Comment by OmarEmaraDev** [comment]
I am sorry, but those aren't official nodes, so we can't provide support there. I think @3DSinghVFX is the one who created those nodes. So better report this to him instead.

**Comment by Yerus** [comment]
He doen't have an issues tab =(

**Comment by 3DSinghVFX** [comment]
> He doen't have an issues tab =(

I have answered your questions in the email :)
