### ISSUE TITLE
Animarion nodes not working

### ISSUE THREAD

**Issue by kenathgreen** [JacquesLucke/animation_nodes#1324]
animation nodes brings back error and doesn't work.
it brings back this error notification

### Error: Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\operators\execute_tree.py", line 21, in execute
    nodeTree.execute()
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\base_types\node_tree.py", line 91, in execute
    self._execute()
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\base_types\node_tree.py", line 104, in _execute
    success = unit.execute()
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes.problems.ExecutionUnitNotSetup

**Comment by OmarEmaraDev** [comment]
Can you share your node tree?

**Comment by kenathgreen** [comment]
![node tree](https://user-images.githubusercontent.com/61118880/74609659-172fde00-50e4-11ea-9d81-cdd8c624b15d.jpg)

![image](https://user-images.githubusercontent.com/61118880/74609684-54946b80-50e4-11ea-9068-dd788cdbdc34.png)

**Comment by kenathgreen** [comment]
I am just a learner right now. please help out however you can. I really wish to know how to use animation nodes

**Comment by OmarEmaraDev** [comment]
What version of Animation Nodes nodes are you using? Where did you download it?

**Comment by kenathgreen** [comment]
Version 4.1.2
On Github

**Comment by OmarEmaraDev** [comment]
I am guessing you mean 2.1.4. I would suggest you update your build by removing it and downloading a new build from here:
https://animation-nodes.com/#download

**Comment by kenathgreen** [comment]
Ill do that now thank you.

**Comment by kenathgreen** [comment]
Its giving me an error

![image](https://user-images.githubusercontent.com/61118880/74610004-3bd98500-50e7-11ea-9b34-c4eab7c2b1a7.png)

**Comment by OmarEmaraDev** [comment]
See #1240.

**Comment by kenathgreen** [comment]
Work perfectly now!!!
Thank you!!!
You are the best!!!

**Comment by OmarEmaraDev** [comment]
That's good to hear. Glad I could help.
