### ISSUE TITLE
Can't install Animation Nodes, numpy.core.multiarray error

### ISSUE THREAD

**Issue by Oddyfox** [JacquesLucke/animation_nodes#1327]
Numpy is for sure installed in my blender/python/lib/site-packages, as I see it myself and have installed using the latest 2.8.2 official release.

What could be causing this?

ImportError: numpy.core.multiarray failed to import

**Comment by OmarEmaraDev** [comment]
Did you download this from blender.org? Which OS are you on?

**Comment by Oddyfox** [comment]
I did download Blender 2.8.2 from Blender.org, or are you asking about the addon itself, which I downloaded from https://blender.community/c/graphicall/Xdbbbc/

I am on Windows 10

**Comment by OmarEmaraDev** [comment]
Can you open the console in Blender and execute `import numpy`?

**Comment by Oddyfox** [comment]
Works fine, it seems.

>>> import numpy
>>> import types
>>> def imports():
...     for name, val in globals().items():
...         if isinstance(val, types.ModuleType):
...             yield val.__name__
...             
>>> import()
  File "<blender_console>", line 1
    import()
          ^
SyntaxError: invalid syntax

>>> imports()
<generator object imports at 0x0000023EF2E0FE48>

>>> np.pi
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
NameError: name 'np' is not defined

>>> numpy.pi
3.141592653589793

>>>

**Comment by OmarEmaraDev** [comment]
Did you install numpy yourself? What is the output of `print(numpy.__path__)`?

**Comment by Oddyfox** [comment]
It was installed using Anaconda at some point separately from Blender

>>> print(numpy.__path__)
['C:\\Users\\OddyF\\AppData\\Roaming\\Python\\Python37\\site-packages\\numpy']

**Comment by OmarEmaraDev** [comment]
I see. Well, that's probably the issue. Blender ships with numpy already, so you don't need to install it manually. I don't exactly know why this happens or how to fix it, but it is not really an issue with Animation Nodes.

Maybe just uninstall that numpy if you don't need it.

**Comment by Oddyfox** [comment]
I would prefer to keep Anaconda since I use it for python programming more often than I use Blender. Is there a way to point Blender to its own included libraries instead of my Python 3.7 folders? I think I tried using the Scripts file path pointer but it still didn't work, but maybe something in that style could work?

**Comment by OmarEmaraDev** [comment]
By default, Blender should use its own python, I have no idea how Anaconda came into the equation.

Personally, I use the System python instead of Blender's. I would suggest you do the same, replace Blender's python with Anaconda completely. See:
https://docs.blender.org/api/current/info_tips_and_tricks.html#bundled-python-extensions

**Comment by Oddyfox** [comment]
First, I copied my python37 site-packages into my Blender2.8.2 python folder (the second option in the link you provided). This did not work, so I proceeded to the first option.

I deleted the python directory in Blender 2.8.2 and updated my PYTHONPATH environment variable accordingly, this also did not work.

It still gives me the same error in the first post, but importing numpy works fine, as it did previously.

I'm going to delete Blender 2.8.2 and uninstall Anaconda temporarily, reinstall Blender 2.8.2 and see if the add-on works.

**Comment by Oddyfox** [comment]
Literally the same error, here's the full readout

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\algorithms\interpolations\__init__.py", line 1, in <module>
    from . implementations import *
  File "animation_nodes\algorithms\interpolations\implementations.pyx", line 1, in init animation_nodes.algorithms.interpolations.implementations
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\data_structures\__init__.py", line 41, in <module>
    dataStructures = importDataStructures()
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\data_structures\__init__.py", line 26, in importDataStructures
    from . sounds.sound import Sound
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\data_structures\sounds\sound.py", line 4, in <module>
    from . sound_sequence import sampleRate
  File "C:\Users\OddyF\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 3, in <module>
    import aud
ImportError: numpy.core.multiarray failed to import

**Comment by OmarEmaraDev** [comment]
I see. Do you get the same output upon importing `aud` in the console?

**Comment by Oddyfox** [comment]
>>> import aud
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import

**Comment by OmarEmaraDev** [comment]
Ok. Well, this seems like an issue with the Audaspace library. You should report this to the Blender tracker instead. Sorry I couldn't help.
