### ISSUE TITLE
Error when using the four basic arithmetic operations buttons on duplicated math node

### ISSUE THREAD

**Issue by meikasahara** [JacquesLucke/animation_nodes#1331]
using the newest Animation Nodes build for linux on Blender 2.82.
Remarks: No crash occured.
Steps to replicate:
1) Create a new animation nodes tree and insert a math node
2)Duplicate the previously inserted node and click on any of the four arithmetic operation buttons
Upon clicking "Add", the following error message was generated:
 
Traceback (most recent call last):
  File "/home/user/.config/blender/2.82/scripts/addons/animation_nodes/operators/dynamic_operators.py", line 52, in invoke_InvokeFunction
    return self.execute(context)
  File "/home/user/.config/blender/2.82/scripts/addons/animation_nodes/operators/dynamic_operators.py", line 58, in execute_InvokeFunction
    self.an_executeCallback(self.callback, *args)
  File "/home/user/.config/blender/2.82/scripts/addons/animation_nodes/extend_bpy_types.py", line 30, in _executeCallback
    executeCallback(callback, *args, **kwargs)
  File "/home/user/.config/blender/2.82/scripts/addons/animation_nodes/operators/callbacks.py", line 25, in executeCallback
    callback(*parameters, args, kwargs)
  File "/home/user/.config/blender/2.82/scripts/addons/animation_nodes/operators/callbacks.py", line 40, in executeNodeCallback
    getattr(node, functionName)(*args, **kwargs)
  File "animation_nodes/nodes/number/float_math.pyx", line 230, in animation_nodes.nodes.number.float_math.FloatMathNode.setOperation
TypeError: bpy_struct: item.attr = val: enum "Add" not found in ('ADD', 'SUBTRACT', 'MULTIPLY', 'DIVIDE', 'SIN', 'COS', 'TANGENT', 'ARCSIN', 'ARCCOSINE', 'ARCTANGENT', 'POWER', 'LOGARITHM', 'MINIMUM', 'MAXIMUM', 'MODULO', 'ABSOLUTE', 'FLOOR', 'CEILING', 'SQUARE_ROOT', 'INVERT', 'RECIPROCAL', 'SNAP', 'ARCTANGENT_B/A', 'HYPOTENUSE', 'COPY_SIGN', 'FLOOR_DIVISION')

location: <unknown location>:-1

**Comment by OmarEmaraDev** [comment]
Thanks for the report! Fixed in 1289cc9.
