### ISSUE TITLE
node animation installing issue

### ISSUE THREAD

**Issue by paratokhs** [JacquesLucke/animation_nodes#1339]
I tried to install node animation addon and when i want to enable it this error shows up.

Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Mohammad\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\Mohammad\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\Mohammad\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\Mohammad\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "D:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Mohammad\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\FastNoiseSIMD\__init__.py", line 1, in <module>
    from . node_base import Noise3DNodeBase
  File "C:\Users\Mohammad\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\libs\FastNoiseSIMD\node_base.py", line 6, in <module>
    from . wrapper import (
ImportError: DLL load failed: The specified module could not be found.

what should i do?

**Comment by OmarEmaraDev** [comment]
See #1240.

**Comment by paratokhs** [comment]
Thank you so much. I really appreciate your help.

> See #1240.
