### ISSUE TITLE
'CurveMap' object has no attribute 'evaluate'

### ISSUE THREAD

**Issue by WKleinschmit** [JacquesLucke/animation_nodes#1374]
Hello,

I was trying to recreate this: https://www.youtube.com/watch?v=WBOuigtl6s4
When I added the "Curve Interpolation" node the following error happended:

Traceback (most recent call last):
  File "C:\Users\w.kleinschmit\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Main'", line 19, in <module>
  File "C:\Users\w.kleinschmit\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\nodes\interpolation\from_curve.py", line 54, in execute
    interpolation = PyInterpolation(curve.evaluate)
AttributeError: 'CurveMap' object has no attribute 'evaluate'

Blend file:
[Countdown.zip](https://github.com/JacquesLucke/animation_nodes/files/4366837/Countdown.zip)

**Comment by OmarEmaraDev** [comment]
There was an API change recently, so you will have to update to the latest Blender and AN versions for this to work.

**Comment by WKleinschmit** [comment]
I'm running Blender 2.82.7 and AN 2.1.4 and I still have that error.

**Comment by OmarEmaraDev** [comment]
2.1.4 is an old version. https://animation-nodes.com/#download
