### ISSUE TITLE
curve interpolation stops the scene

### ISSUE THREAD

**Issue by Tomonomicon** [JacquesLucke/animation_nodes#1388]
just adding in a curve interpolation node just stops all everything that the animation nodes are doing. you can still move objects around in the scene but the moment i create a curve interpolation node it stops everything, the node isn't even connected to anything

this was in the problems listed in the console: 

Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 97, in <module>
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\nodes\interpolation\from_curve.py", line 54, in execute
    interpolation = PyInterpolation(curve.evaluate)
AttributeError: 'CurveMap' object has no attribute 'evaluate'

Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 97, in <module>
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\nodes\interpolation\from_curve.py", line 54, in execute
    interpolation = PyInterpolation(curve.evaluate)
AttributeError: 'CurveMap' object has no attribute 'evaluate'

**Comment by OmarEmaraDev** [comment]
This was fixed in a51e572. We would need the latest Blender and Animation Nodes version for this to work.
