### ISSUE TITLE
Compiling AN Centos 7 ZN22FastNoiseSIMD

### ISSUE THREAD

**Issue by GiorgioAdolfo** [JacquesLucke/animation_nodes#1417]
Hello, i tried to compile AN on Centos 7 and got this:

Traceback (most recent call last): File "/opt/Autodesk/flame_2021/blender-2.83-839fe335d2d6-linux64/2.83/scripts/modules/addon_utils.py", line 351, in enable mod = import(module_name) File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/init.py", line 166, in <module> auto_load.init() File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 23, in init modules = get_all_submodules(Path(file).parent) File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 51, in get_all_submodules return list(iter_submodules(directory, directory.name)) File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 55, in iter_submodules yield importlib.import_module("." + name, package_name) File "/opt/Autodesk/flame_2021/blender-2.83-839fe335d2d6-linux64/2.83/python/lib/python3.7/importlib/init.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/init.py", line 1, in <module> from . node_base import Noise3DNodeBase File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/node_base.py", line 6, in <module> from . wrapper import ( ImportError: /opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/wrapper.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN22FastNoiseSIMD_internal16FastNoiseSIMD_L3C1Ei</module></module></module>

Any help would be appreciated!
Thank you!

**Comment by GiorgioAdolfo** [comment]
It compiles, with no errors, but when i try to load the addon i gotthis:
Copied from the blender console. Blender 2.83 Centos 7

Modules Installed (animation_nodes) from '/opt/Autodesk/flame_2021/AN_Build/animation_nodes-master/animation_nodes_v2_1_linux_py37.zip' into '/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons'
Traceback (most recent call last):
  File "/opt/Autodesk/flame_2021/blender-2.83-839fe335d2d6-linux64/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/__init__.py", line 166, in <module>
    auto_load.init()
  File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/opt/Autodesk/flame_2021/blender-2.83-839fe335d2d6-linux64/2.83/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/__init__.py", line 1, in <module>
    from . node_base import Noise3DNodeBase
  File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/node_base.py", line 6, in <module>
    from . wrapper import (
ImportError: /opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/wrapper.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN22FastNoiseSIMD_internal16FastNoiseSIMD_L3C1Ei

**Comment by OmarEmaraDev** [comment]
I don't know the cause of this off the top of my head, but I will try to debug it as soon as I have the time.
