### ISSUE TITLE
Can't activate anymore

### ISSUE THREAD

**Issue by ogierm** [JacquesLucke/animation_nodes#1447]
I'm building the add-on myself to keep up to date. Today I noticed that I can't activate the add-on, because it can't find `offsetColors`, it's a function in of these python files that are being compiled to C. I shortly looked into it, but didn't saw any obvious issues related to the error message.
Am on Blender 2.90, Windows 10

**Comment by OmarEmaraDev** [comment]
Can you attach the exact error message?

**Comment by ogierm** [comment]
```
Traceback (most recent call last):
  File "C:\Blender Foundation\daily\blender-2.90.0-9f7d84b656fb-windows64\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Bent\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\Bent\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\Bent\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\Bent\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Blender Foundation\daily\blender-2.90.0-9f7d84b656fb-windows64\2.90\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Bent\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\animation_nodes\nodes\gpencil\offset_gp_stroke.py", line 3, in <module>
    from .. color.c_utils import offsetColors
ImportError: cannot import name 'offsetColors' from 'animation_nodes.nodes.color.c_utils' (C:\Users\Bent\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\animation_nodes\nodes\color\c_utils.cp37-win_amd64.pyd)
```

**Comment by OmarEmaraDev** [comment]
I can replicate the issue. But I am on Linux. Does the Windows build we provide work?

**Comment by ogierm** [comment]
Which one should I pick? They haven't been updated in a while.

**Comment by OmarEmaraDev** [comment]
@ogierm https://animation-nodes.com/#download

**Comment by ogierm** [comment]
That version works

**Comment by OmarEmaraDev** [comment]
Then you are probably compiling AN wrongly. Can you outline the method you used to compile AN?

**Comment by ogierm** [comment]
I've cloned the repository and then run `python setup.py build` after each pull. I have a symlink that leads into the Blender versions add-on directory in %appdata%. I've been doing it this way since probably 2+ years.

**Comment by OmarEmaraDev** [comment]
Sometimes it is necessary to do a clean compile from scratch. So if you haven't tried that, you should try it.

If the issue persists, try to look at the symbols in the the `c_utils.*.dll` file and check if you can find the function there. I am not sure how one can do that on Windows though.

**Comment by ogierm** [comment]
Cleaned and did a recompile and got this one
```
Traceback (most recent call last):
  File "C:\Blender Foundation\daily\blender-2.90.0-9f7d84b656fb-windows64\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Bent\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\animation_nodes\__init__.py", line 158, in <module>
    raise Exception(message)
Exception: 

This build does not work at the moment.
  1. Check if the build you downloaded has been compiled for the OS
     you are using. If not, download another one.
  2. If you are on windows you can try to install a library called
     'vc_redist.x64'. Should be easy to find using your search engine
     of choice.
  3. Try to use an official Blender release downloaded from blender.org.
  4. It is possible that you have a build for the correct platform
     but it still does not work. We experienced this mainly on linux.
     Try to find another build for your platform.
     If it still does not work, you have to compile AN yourself.
  5. Make a bug report on Github and give as much information
     as you can. Specifically the full error message, your OS, version, ...

```

**Comment by ogierm** [comment]
![image](https://user-images.githubusercontent.com/29630575/84595510-91852a80-ae58-11ea-97b9-6efb8bb1b6b7.png)
Not sure how this should look, but isn't this correct?

**Comment by OmarEmaraDev** [comment]
As far as I know, Blender 2.90 uses Blender 3.7, while you seem to be compiling with 3.8. Is that the case? If not, then your versions should match.

**Comment by ogierm** [comment]
Yes I'm using 3.8, but that worked for 4 months or so. I'll try it with 3.7, but as far as I know there are no upwards incompatibilities.

**Comment by ogierm** [comment]
Compiling with 3.7 worked. 🤷‍♀️
