### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by collinizhou** [JacquesLucke/animation_nodes#1448]
I had a problem when install animation nodes. Belnder version 2.83. please help me,think you!

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animation_nodes\libs\FastNoiseSIMD\__init__.py", line 1, in <module>
    from . node_base import Noise3DNodeBase
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animation_nodes\libs\FastNoiseSIMD\node_base.py", line 6, in <module>
    from . wrapper import (
ImportError: DLL load failed: 找不到指定的模块。

**Comment by 3DSinghVFX** [comment]
Hi. I think you need to install `vc_redist.x64` and for information see **Import Error: DLL load failed** https://github.com/JacquesLucke/animation_nodes/issues/1240

**Comment by collinizhou** [comment]
think you!
i installed vc_redist.x64, But the same error message still appears。

**Comment by collinizhou** [comment]
think you!
i installed vc_redist.x64, But the same error message still appears。

**Comment by OmarEmaraDev** [comment]
Can you try installing it as an administrator?

**Comment by collinizhou** [comment]
i tried install it as an administrator,can't solve this problem.

**Comment by OmarEmaraDev** [comment]
Did you reboot your system? If you didn't, I suggest you do, otherwise, I am not sure what could be causing this.

**Comment by collinizhou** [comment]
yes,i reboot my computer,Error prompt of same message was still here.how can i do?

**Comment by cxdcxdcxd198** [comment]
https://blender.community/c/graphicall
Download AN compiled file from this link. you can not install the zip that cloned from git!

**Comment by OmarEmaraDev** [comment]
@cxdcxdcxd198 Please use builds from http://animation-nodes.com/#download instead.

**Comment by cxdcxdcxd198** [comment]
@OmarEmaraDev Roger that :D
