### ISSUE TITLE
Wiggle Action Node Error!

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1459]
![wiggle action error](https://user-images.githubusercontent.com/64368228/85871619-43313d80-b801-11ea-961e-c27cbad0b833.png)

the path does not surport like  the "location" 3 dimensions attribute, and gave this error:
```
Traceback (most recent call last):
  File "/home/sten/blender-2.83.0-linux64/2.83/scripts/addons_contrib/animation_nodes/execution/main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 12, in <module>
  File "animation_nodes/nodes/action/object_action_output.pyx", line 69, in animation_nodes.nodes.action.object_action_output.ObjectActionOutputNode.execute_Generic_Single
  File "animation_nodes/nodes/action/object_action_output.pyx", line 80, in animation_nodes.nodes.action.object_action_output.ObjectActionOutputNode.execute_Generic_List
  File "animation_nodes/nodes/action/object_action_output.pyx", line 144, in animation_nodes.nodes.action.object_action_output.ObjectActionOutputNode.execute_RawChannels
  File "<string>", line 2, in setter
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'float'
```
is this a bug for this node? or something others reason?

**Comment by OmarEmaraDev** [comment]
It seem this particular node doesn't do much graceful exception handing, so we will have to deal with that.

**Comment by OmarEmaraDev** [comment]
I added a generic error for now in ccaf50d. We can make the error messages more granular in the future, but I don't want to mess with the code at this point.
