### ISSUE TITLE
Use of undeclared identifier 'gl_FragColor'

### ISSUE THREAD

**Issue by don1138** [JacquesLucke/animation_nodes#1555]
I have a scene with a cube.

I add a **Mesh Object Input** node, select cube as object.

Add **Mesh Points Scatter** node, connect MOI *Mesh* output to MPS *Mesh* input.

Add **3D Viewer** node, connect MPS *Matrices* output to 3DV *Data* input.

No effect.

I get this error message in console:

```
GPUShader: compile error:
ERROR: 0:94: Use of undeclared identifier 'gl_FragColor'

Traceback (most recent call last):
  File "/Users/User/Library/Application Support/Blender/2.83/scripts/addons/animation_nodes/nodes/viewer/viewer_3d.py", line 127, in draw
    drawData.drawFunction(drawData.data)
  File "/Users/User/Library/Application Support/Blender/2.83/scripts/addons/animation_nodes/nodes/viewer/viewer_3d.py", line 97, in drawMatrices
    shader = getShader(os.path.join(os.path.dirname(__file__), "matrix_shader.glsl"))
  File "/Users/User/Library/Application Support/Blender/2.83/scripts/addons/animation_nodes/graphics/import_shader.py", line 10, in getShader
    return gpu.types.GPUShader("\n".join(lines[:i]), "\n".join(["\n"] * index + lines[i:]))
Exception: Shader Compile Error, see console for more details
```

 
Animation Nodes 2.2.1
Blender 2.83.7 and 2.90.1
MacOS 10.15.7

**Comment by OmarEmaraDev** [comment]
Fix in 237269e. Thanks for the report!
