### ISSUE TITLE
Execution stops working wihout any message.

### ISSUE THREAD

**Issue by akaflokart** [JacquesLucke/animation_nodes#1576]
Hi,
only if i hit the execution button everything works as expected but no more trigger or anthing else.
I used 
``` python
bpy.ops.an.execute_tree(name="NodeTree.002")
````
in another nodetree script maybe thats the reason.
I have no idea how i could fix this.
console spits out.

```
Error: Traceback (most recent call last):
  File "C:\Users\Florian\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\operators\output_execution_code.py", line 14, in execute
    code = getCurrentExecutionCode(lineNumbers = True)
  File "C:\Users\Florian\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\operators\output_execution_code.py", line 46, in getCurrentExecutionCode
    codes = unit.getCodes()
AttributeError: 'NoneType' object has no attribute 'getCodes'

location: <unknown location>:-1
```

**Comment by OmarEmaraDev** [comment]
Can you share the file that reproduces the issue?
