### ISSUE TITLE
[KeyError: 10] when "Read Midi File" Node parses some midi file

### ISSUE THREAD

**Issue by Hansimov** [JacquesLucke/animation_nodes#1726]
When I try to parse a midi file ([canon-2-03m02s.zip](https://github.com/JacquesLucke/animation_nodes/files/6524237/canon-2-03m02s.zip)) with the "Read MIDI File" Node, it raises `KeyError: 10` as shown below (at last line):
- It seems that some event in this midi file is not covered and recognized by the script
- Or maybe it parses some previous bytes incorrectly so that it takes the subsequent byte "10" as an event number, which in fact is not a valid input
- I use Blender 2.92 and Animation Nodes 2.2.2

```
Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'AN Tree'", line 5, in <module>
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\nodes\sound\midi_file_reader.py", line 33, in execute
    return readMIDIFile(path)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\utils\midi.py", line 15, in readMIDIFile
    return readMIDIFileCached(path, lastModification)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\utils\midi.py", line 107, in readMIDIFileCached
    midiFile = MidiFile.fromFile(path)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 143, in fromFile
    tracks = parseTracks(memoryMap, tracksCount)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 130, in parseTracks
    return [MidiTrack.fromMemoryMap(memoryMap) for i in range(tracksCount)]
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 130, in <listcomp>
    return [MidiTrack.fromMemoryMap(memoryMap) for i in range(tracksCount)]
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 118, in fromMemoryMap
    events = parseEvents(memoryMap)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 101, in parseEvents
    event = parseEvent(memoryMap, parseState)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 87, in parseEvent
    return parseMetaEvent(deltaTime, memoryMap)
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\libs\midiparser\parser.py", line 67, in parseMetaEvent
    eventClass = metaEventByType[eventType]
KeyError: 10
```

**Comment by OmarEmaraDev** [comment]
I feel like this might be a wrong implementation of running status. I will investigate this later.

Thanks for the report!

**Comment by OmarEmaraDev** [comment]
I looked at this many times and I would just say this file is either corrupt or non standard conforming.

A hex dump of the first part of the the first track is as follows:

```hex
00 ff  08 08 43 61 6e 6f 6e 20  44 00 00 ff 0a 10 4a 6f  68 61 6e 6e 20 50 61 63  68 65 62 65 6c 00
``` 

Which is parsed as follows:

```hex
00 -> Delta time of zero.
FF -> Meta Event
08 -> Program Name Event
08 -> 8 ASCII characters will follow.
43 61 6e 6f 6e 20  44 00 -> Canon D\x00
00 -> Delta time of zero.
FF -> Meta Event
0a -> (Bad byte, there is no Meta Event of type 0a)
```

I looked all over for this `0a` meta event and I found nothing, so I will just close this, if anyone known anything about this, let me know and we will look into it.

**Comment by Hansimov** [comment]
@OmarEmaraDev Thanks for your great efforts!
I also guess that it is not a standard format, although it can be played by some MIDI players like Synthesia.

**Comment by iyadahmed** [comment]
Idk if these help, don't know much about MIDI
https://stackoverflow.com/questions/43321950/synthesia-plays-well-midi-file-without-any-note-off-event

http://www.music.mcgill.ca/~ich/classes/mumt306/StandardMIDIfileformat.html
Appendix 1.2 - Table of MIDI Controller Messages (Data Bytes)
![image](https://user-images.githubusercontent.com/25552173/129485043-c6ed8298-98ef-44fc-b7b3-e96e22efe92e.png)

**Comment by OmarEmaraDev** [comment]
@iyadahmed Controller events are Channel events, not Meta events, so their status byte has to be `Bn`, which is not the case here. So this table is not exactly relevant to our case.

@Hansimov This unknown event does provide its length, so a possible solution is to just ignore all of its bytes and jump to the next event. Since meta events don't affect running status, this should have no effect on the rest of the parsing. I will look into this workaround.

**Comment by iyadahmed** [comment]
> @iyadahmed Controller events are Channel events, not Meta events, so their status byte has to be `Bn`, which is not the case here. So this table is not exactly relevant to our case.
> 
> @Hansimov This unknown event does provide its length, so a possible solution is to just ignore all of its bytes and jump to the next event. Since meta events don't affect running status, this should have no effect on the rest of the parsing. I will look into this workaround.

ah ok got it
