### ISSUE TITLE
Not sure if a bug, but those are no redbars, and nodes don't work like they should.

### ISSUE THREAD

**Issue by genesis2303** [JacquesLucke/animation_nodes#1734]
Bug is in 02:49, haven't seen this before.
https://streamable.com/uu93zi
Restarting blender as usual helped, but this one I haven't seen yet.

**Comment by OmarEmaraDev** [comment]
Seems like Animation Nodes stopped working completely. Were there any errors in the terminal?

**Comment by genesis2303** [comment]
I didn't go to terminal, just restarted blender it helps with redbars and this seemed similar.

**Comment by genesis2303** [comment]
When this error showed I was using Blender alpha from last Friday, and latest Extra nodes. Other than that I was using rigid body, and moved key frames before 0 on timeline. I saw it first time, but I'll try to reproduce it tomorrow.

**Comment by genesis2303** [comment]
Reproduced it:
1. I dropped the object with rigid body on the plane.
2. I baked dynamics.
3. Called object id key node and it's dark gray not working properly just like earlier.

In terminal, I don't see anything AN related just Sverchock errors and polygon material add-on errors.

**Comment by OmarEmaraDev** [comment]
Does this happen with official AN?

**Comment by genesis2303** [comment]
Just tried it, and no, so it would be extra nodes, or bluefox extension issue.

**Comment by genesis2303** [comment]
Weird after installing Official AN and next getting back to Extra nodes I can no longer reproduce it.

**Comment by OmarEmaraDev** [comment]
I am not sure if Extra nodes or Bluefox do anything special, so I am not sure about this issue.

**Comment by genesis2303** [comment]
Well I'm sure it exists, I can't make up code, but to reproduce it I have to repeat a lot of steps. I don't always work with simple example, it sometimes shows up, sometimes not. I cut quite few letters since yesterday to spot it. 
```
Python: Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\sverchok-master\ui\sv_IO_panel.py", line 295, in poll
    return bool(context.space_data.node_tree)
AttributeError: 'SpaceView3D' object has no attribute 'node_tree'

location: <unknown location>:-1
Baked for 23s, current frame: 250/250 (0.083s), ETC: 0ss
Bake finished in 23s (250 frames simulated).
Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\utils\handlers.py", line 71, in frameChangedPost
    handler(scene, depsgraph)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\events.py", line 39, in frameChanged
    event_handler.update(event.getActives().union({"Frame"}))
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\utils\recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\event_handler.py", line 23, in update
    executeNodeTrees(nodeTrees)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\execution\auto_execution.py", line 13, in executeNodeTrees
    nodeTree.autoExecute()
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\base_types\node_tree.py", line 82, in autoExecute
    self._execute()
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\base_types\node_tree.py", line 106, in _execute
    self.lastExecutionInfo.executionTime = end - start
AttributeError: Writing to ID classes in this context is not allowed: Main, NodeTree datablock, error setting LastTreeExecutionInfo.executionTime
```

**Comment by OmarEmaraDev** [comment]
What if you disable Animation Nodes during baking?

**Comment by genesis2303** [comment]
Auto execution or AN add-on completely?

**Comment by OmarEmaraDev** [comment]
Auto execution.

**Comment by genesis2303** [comment]
Disabled autoexecution, during bake terminal says this, but I don't see baking entry despite in other time it was.
```
location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\sverchok-master\ui\sv_IO_panel.py", line 295, in poll
    return bool(context.space_data.node_tree)
AttributeError: 'SpaceView3D' object has no attribute 'node_tree'

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\utils\handlers.py", line 71, in frameChangedPost
    handler(scene, depsgraph)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\events.py", line 39, in frameChanged
    event_handler.update(event.getActives().union({"Frame"}))
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\utils\recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\event_handler.py", line 23, in update
    executeNodeTrees(nodeTrees)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\execution\auto_execution.py", line 13, in executeNodeTrees
    nodeTree.autoExecute()
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\base_types\node_tree.py", line 82, in autoExecute
    self._execute()
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\base_types\node_tree.py", line 106, in _execute
    self.lastExecutionInfo.executionTime = end - start
AttributeError: Writing to ID classes in this context is not allowed: RaccoonGraphics, NodeTree datablock, error setting LastTreeExecutionInfo.executionTime

```

**Comment by OmarEmaraDev** [comment]
Are you sure it is disabled? The `frameChangedPost` handler executes upon frame changes if auto execution is enabled, which is shown here.

**Comment by genesis2303** [comment]
This time should be turned off:

https://i.imgur.com/jRd9bj3.png

Before I bake nodes are normal.

`location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\sverchok-master\ui\sv_IO_panel.py", line 295, in poll
    return bool(context.space_data.node_tree)
AttributeError: 'SpaceView3D' object has no attribute 'node_tree'

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\utils\handlers.py", line 71, in frameChangedPost
    handler(scene, depsgraph)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\events.py", line 39, in frameChanged
    event_handler.update(event.getActives().union({"Frame"}))
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\utils\recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\event_handler.py", line 23, in update
    executeNodeTrees(nodeTrees)
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\execution\auto_execution.py", line 13, in executeNodeTrees
    nodeTree.autoExecute()
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\base_types\node_tree.py", line 82, in autoExecute
    self._execute()
  File "C:\Users\Gamer\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\base_types\node_tree.py", line 106, in _execute
    self.lastExecutionInfo.executionTime = end - start
AttributeError: Writing to ID classes in this context is not allowed: RaccoonGraphics, NodeTree datablock, error setting LastTreeExecutionInfo.executionTime
`

**Comment by genesis2303** [comment]
Ok I missed two presets still working. I'm sorry I just cut too many letters today. When execution disabled completely they behave normal, and I'm able to turn execution on after baking. I tried also with just AN main tree (preset trees off) but then it comes back.
