### ISSUE TITLE
Unable to enable animation nodes

### ISSUE THREAD

**Issue by Consoli0** [JacquesLucke/animation_nodes#1739]
I'm not sure what I'm doing wrong, or if I'm on the wrong version, but I'm attempting to use Animation Nodes 2.2.2 in Blender 2.93.0 (Steam version), and I'm getting an error that gives me no information on what to do.

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\boop\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\boop\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\boop\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\boop\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\boop\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\nodes\mesh\generation\unity_triangle.py", line 35, in <module>
    mesh = Mesh(vertexLocations, edgeIndices, polygonIndices, materialIndices, skipValidation = True)
  File "animation_nodes\data_structures\meshes\mesh_data.pyx", line 55, in animation_nodes.data_structures.meshes.mesh_data.Mesh.__cinit__
TypeError: __cinit__() got multiple values for keyword argument 'skipValidation'
```

**Comment by OmarEmaraDev** [comment]
Can you try manually removing the `animation_nodes` folder from the blender addon directory and installing it again?
