### ISSUE TITLE
Bug Report Running animation nodes with Shipwright

### ISSUE THREAD

**Issue by droddy386** [JacquesLucke/animation_nodes#1752]
Traceback (most recent call last):
  File "C:\Users\drodd\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Shipwright Generator'", line 13, in <module>
  File "group: 'Shape Generator Group'", line 42, in main
  File "group: 'My Loop'", line 140, in main
  File "C:\Users\drodd\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\an_shape_generator\node_shape_generator.py", line 242, in execute
    mesh_to_return.insertAttribute(Attribute("UVMap", AttributeType.UV_MAP, AttributeDomain.CORNER,
AttributeError: 'animation_nodes.data_structures.meshes.mesh_data.M' object has no attribute 'insertAttribute'

Start running the Animation Nodes test suite.
Can be disabled in the user preferences of the addon.

.................................................................................................................................................................................................................................................................................................F..F...........................................................................................................
======================================================================
FAIL: testSingleSegmentBothParametersZero (animation_nodes.data_structures.splines.test_bezier_spline.TestGetTrimmedCopy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\drodd\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\data_structures\splines\test_bezier_spline.py", line 76, in testSingleSegmentBothParametersZero
    self.assertTrue(len(newSpline.points) >= 1)
AssertionError: False is not true

======================================================================
FAIL: testSingleSegmentSameParameter (animation_nodes.data_structures.splines.test_bezier_spline.TestGetTrimmedCopy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\drodd\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\animation_nodes\data_structures\splines\test_bezier_spline.py", line 69, in testSingleSegmentSameParameter
    self.assertTrue(len(newSpline.points) >= 1)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 400 tests in 0.025s

FAILED (failures=2)

Time: 0.03125 - fps : 32.00 - Function: update
Time: 0.03125 - fps : 32.00 - Function: updateEverything

**Comment by OmarEmaraDev** [comment]
Shipwright doesn't seem to be compatible with the latest version of Animation Nodes, because change the attribute API. We are doing a release soon, so I guess the addon will be updated then. Either way, you should notify the developer of Shipwright instead. As for the tests, I will fix those, but they are not related to your problem.

**Comment by droddy386** [comment]
Understood.  Problem solved.  Thanks.
