### ISSUE TITLE
Can't enable animation nodes - macOS - Blender 2.93

### ISSUE THREAD

**Issue by deanemorris** [JacquesLucke/animation_nodes#1768]
Blender 2.93 LTS
MacOS Catalina 10.15.7 (19H1323)
When I try to enable animation nodes (latest build - July 30, 2021):

Traceback (most recent call last):
  File "/Applications/Blender/Blender 2.93.0 LTS/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/Users/deanemorris/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/__init__.py", line 172, in register
    auto_load.register()
  File "/Users/deanemorris/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/auto_load.py", line 28, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "an_InterpolationListSocket" registration error: display could not register

compilation_info.json:
{
  "Cython.__version__": "0.29.23",
  "date": 1625212719,
  "os.name": "posix",
  "sys.api_version": 1013,
  "sys.platform": "darwin",
  "sys.version": "3.9.5 (default, May 25 2021, 07:41:55) \n[Clang 11.0.0 (clang-1100.0.33.17)]",
  "sys.version_info": [
    3,
    9,
    5,
    "final",
    0
  ]
}

**Comment by deanemorris** [comment]
Sorry... This should have been for the 3DSinghVFX fork.  
I am just trying to get animation nodes running in Blender 2.93LTS and I can't find a way to do it.
I am giving up.
