### ISSUE TITLE
AN v2.2 error on blender 2.93 linux

### ISSUE THREAD

**Issue by lzli3s** [JacquesLucke/animation_nodes#1785]
AN on blender 2.93.4 Ubuntu 18.04 works unstable(Install > restart blender AN works okay > restart blender AN does not work anymore)
Logs from blender:
Exception in module unregister(): '/home/ubuntu/.config/blender/2.93/scripts/addons/animation_nodes/__init__.py'
Traceback (most recent call last):
  File "/home/ubuntu/app/blender/2.93/scripts/modules/addon_utils.py", line 438, in disable
    mod.unregister()
  File "/home/ubuntu/.config/blender/2.93/scripts/addons/animation_nodes/__init__.py", line 176, in unregister
    auto_load.unregister()
  File "/home/ubuntu/.config/blender/2.93/scripts/addons/animation_nodes/auto_load.py", line 38, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

**Comment by OmarEmaraDev** [comment]
This is a harmless error as far as I know, which we have't found the cause to yet. How does it not work exactly?

**Comment by lzli3s** [comment]
After installing AN V2.3 It works now. Thanks.
