### ISSUE TITLE
v2.2.2 not working on centos 7.9 with blender 2.93.x

### ISSUE THREAD

**Issue by youmcheck** [JacquesLucke/animation_nodes#1786]
Hi, 
enable animation nodes result return this error:

_Traceback (most recent call last):
  File "/usr/local/blender-2.93.2-circus/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/mnt/W_Workgroups/workgroups/REZ/blender_third_party/animation_nodes/2.2.2/addon/animation_nodes/__init__.py", line 166, in <module>
    auto_load.init()
  File "/mnt/W_Workgroups/workgroups/REZ/blender_third_party/animation_nodes/2.2.2/addon/animation_nodes/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/mnt/W_Workgroups/workgroups/REZ/blender_third_party/animation_nodes/2.2.2/addon/animation_nodes/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/mnt/W_Workgroups/workgroups/REZ/blender_third_party/animation_nodes/2.2.2/addon/animation_nodes/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/usr/local/blender-2.93.2-circus/2.93/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/mnt/W_Workgroups/workgroups/REZ/blender_third_party/animation_nodes/2.2.2/addon/animation_nodes/libs/FastNoiseSIMD/__init__.py", line 1, in <module>
    from . node_base import Noise3DNodeBase
  File "/mnt/W_Workgroups/workgroups/REZ/blender_third_party/animation_nodes/2.2.2/addon/animation_nodes/libs/FastNoiseSIMD/node_base.py", line 6, in <module>
    from . wrapper import (
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /mnt/W_Workgroups/workgroups/REZ/blender_third_party/animation_nodes/2.2.2/addon/animation_nodes/libs/FastNoiseSIMD/wrapper.cpython-39-x86_64-linux-gnu.so)_

Best

**Comment by OmarEmaraDev** [comment]
Did you build AN yourself or download a build?

**Comment by youmcheck** [comment]
hi, Yes we compil ourself blender as with the release makefile provide by blender and the library or centos7 provide d by blender too. we only compile separatly the bpy modul for pyrhon.thanks for quick reply,ArnaudLe 10 sept. 2021 16:58, Omar Emara ***@***.***> a écrit :
Did you build AN yourself or download a build?

**Comment by OmarEmaraDev** [comment]
I was talking about Animation Nodes. Do you build Animation Nodes yourself?

**Comment by OmarEmaraDev** [comment]
See #1692.

**Comment by youmcheck** [comment]
no we do not compile animation node ourselfLe 10 sept. 2021 19:42, Omar Emara ***@***.***> a écrit :
I was talking about Animation Nodes. Do you build Animation Nodes yourself?

**Comment by OmarEmaraDev** [comment]
The builds we have on the website will likely not work with CentOS, so you will have to build it yourself, possibly using a newer  compiler toolchain because the CentOS compiler is too old to compile Animation Nodes.

**Comment by youmcheck** [comment]
ok I will try to recompil thanks for reply,bestLe 13 sept. 2021 10:36, Omar Emara ***@***.***> a écrit :
The builds we have on the website will likely not work with CentOS, so you will have to build it yourself, possibly using a newer  compiler toolchain because the CentOS compiler is too old to compile Animation Nodes.
