### ISSUE TITLE
animation_nodes.problems.ExecutionUnitNotSetup

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/animation_nodes#1794]
Hi

I set up a simple network and this is what I get. It seems to me at some point it crashed and pressing "retry" does not do anything.

![blender_bbkRI51EwL](https://user-images.githubusercontent.com/8519469/135903311-bc79d755-ac53-4d24-9ce7-e4c5a315f6b8.jpg)

```
Blender 3.0.0 Alpha
        build date: 2021-10-04
        build time: 08:23:56
        build commit date: 2021-10-04
        build commit time: 07:43
        build hash: 8c55333a8e80
        build platform: Windows
        build type: release
```

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\operators\profiling.py", line 16, in execute
    result = self.getProfilingResult()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\operators\profiling.py", line 31, in getProfilingResult
    cProfile.runctx("function()", d, d, sort = self.sort)
  File "C:\BLENDER\3.0\python\lib\cProfile.py", line 19, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
  File "C:\BLENDER\3.0\python\lib\profile.py", line 62, in runctx
    prof.runctx(statement, globals, locals)
  File "C:\BLENDER\3.0\python\lib\cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\operators\profiling.py", line 37, in executeFunction
    execute_TreeExecutiong()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\operators\profiling.py", line 54, in execute_TreeExecutiong
    bpy.context.space_data.edit_tree.execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\base_types\node_tree.py", line 89, in execute
    self._execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\base_types\node_tree.py", line 102, in _execute
    success = unit.execute()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes.problems.ExecutionUnitNotSetup

location: <unknown location>:-1
```

**Comment by OmarEmaraDev** [comment]
Can you reliably reproduce the issue in a new file?

**Comment by gerroon** [comment]
No not directly. I will report if I can
