### ISSUE TITLE
Expression Node empty expression results in python script exception

### ISSUE THREAD

**Issue by s-light** [JacquesLucke/animation_nodes#188]
```
stefan@stefan-pc:~$ /home/stefan/blender/blender-2.75a-linux-glibc211-x86_64/blender
connect failed: No such file or directory
Read new prefs: /home/stefan/.config/blender/2.75/config/userpref.blend
found bundled python: /home/stefan/blender/blender-2.75a-linux-glibc211-x86_64/2.75/python
Registered Animation Nodes with 213 modules.
Traceback (most recent call last):
  File "/home/stefan/.config/blender/2.75/scripts/addons/animation_nodes-master/mn_execution.py", line 119, in nodeTreeChanged
    generateExecutionUnits()
  File "/home/stefan/.config/blender/2.75/scripts/addons/animation_nodes-master/mn_execution.py", line 84, in generateExecutionUnits
    executionUnits = getExecutionUnits()
  File "/home/stefan/.config/blender/2.75/scripts/addons/animation_nodes-master/mn_execution_unit_generator.py", line 103, in getExecutionUnits
    executionUnit = ExecutionUnit(codeGenerator.generatedCode, codeGenerator.updateSettingsNode)
  File "/home/stefan/.config/blender/2.75/scripts/addons/animation_nodes-master/mn_execution_unit_generator.py", line 18, in __init__
    self.codeObject = compile(code, "<string>", "exec")
  File "<string>", line 16
    try: output_0_result =  
                           ^
SyntaxError: invalid syntax
File "/home/stefan/.config/blender/2.75/scripts/addons/animation_nodes-master/mn_execution.py", line 118, in nodeTreeChanged
```
i think there should be a check for an empty string in
[mn_execution_unit_generator.py#L18](https://github.com/JacquesLucke/animation_nodes/blob/master/mn_execution_unit_generator.py#L18)
or in [mn_utils.py isValidCode()](https://github.com/JacquesLucke/animation_nodes/blob/master/mn_utils.py#L151)
--> for the ast.parse a empty string is valid!!
but you rely on a non empty sting in [expression.py#L82 getExecutionCode()](https://github.com/JacquesLucke/animation_nodes/blob/refactor/nodes/script/expression.py#L82)

**Comment by JacquesLucke** [comment]
Thanks for the report. I will fix it as soon as I'm at home again :)
