### ISSUE TITLE
problems with blender 3.4.0

### ISSUE THREAD

**Issue by jamestomk** [JacquesLucke/animation_nodes#1896]
it's been a while since I've used AN,  but in using AN 2.3.0 with blender 3.4.0 I'm getting lots of errors when trying to add nodes.  I just tried to add a Move node and got the following.  Similar with many other nodes.

```
Python: Traceback (most recent call last):
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\animation_nodes\ui\node_search.py", line 37, in execute
    itemsByIdentifier[self.item].insert()
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\animation_nodes\ui\node_search.py", line 86, in insert
    node = newNodeAtCursor(self.idName)
  File "C:\Users\James\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\animation_nodes\utils\nodes.py", line 4, in newNodeAtCursor
    bpy.ops.node.add_and_link_node(type = type)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.node.add_and_link_node" error, could not be found
```

**Comment by OmarEmaraDev** [comment]
We fixed that issue before, are you sure you have the latest version installed?

**Comment by uraniumcrystalsmaster** [comment]
I'm having the same issue as jamestomk, and I have the same version of geometry nodes they has, which is 2.3.0. Here's a link to the description of the problem I've encountered: https://blender.stackexchange.com/questions/283039/animation-node-search-library-present-in-geometry-nodes-problem/283040#283040
