### ISSUE TITLE
Bmesh Mesh node is not working

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1914]
The Bmesh Mesh node is not working, it does not output Edge and Polygon Indices. 
![AN_Issue](https://user-images.githubusercontent.com/30294746/235350237-57ab5690-5181-4f85-bcaa-b8b53b3782cb.png)

```
Traceback (most recent call last):
  File "/home/kuldeep/.config/blender/3.5/scripts/addons/animation_nodes/execution/main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'AN Tree'", line 16, in <module>
  File "/home/kuldeep/.config/blender/3.5/scripts/addons/animation_nodes/nodes/mesh/bmesh_mesh_data.py", line 42, in getEdgeIndices
    return EdgeIndicesList.fromValues(tuple(v.index for v in edge.verts) for edge in bMesh.edges)
  File "animation_nodes/data_structures/lists/base_lists.pyx", line 10464, in animation_nodes.data_structures.lists.base_lists.EdgeIndicesList.fromValues
  File "animation_nodes/data_structures/lists/base_lists.pyx", line 10215, in animation_nodes.data_structures.lists.base_lists.EdgeIndicesList.extend

```

**Comment by OmarEmaraDev** [comment]
Fixed in 821d52926462c9371a7a0ab6002bad6c1b749999.
