### ISSUE TITLE
failed to enable the addon

### ISSUE THREAD

**Issue by ivanmmz** [JacquesLucke/animation_nodes#1946]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Ivan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\animation_nodes\__init__.py", line 137, in <module>
    raise Exception(message)
Exception: 

There is a Python version mismatch.

Your Blender build uses: (3, 10, 13)
Animation Nodes has been compiled for: (3, 11, 7)

You have three options:
  1. Try to make Blender use another Python version.
     (Blender 2.93 officially uses Python 3.9.x)
  2. Compile Animation Nodes yourself using the correct Python version.
     (Look in the developer manual for more information)
  3. Create an issue on Github and ask if someone can create a build for you.

**Comment by OmarEmaraDev** [comment]
Download the py310 version from here. https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build

**Comment by ivanmmz** [comment]
May I know after downloading what should I do? I tried downloading a few versions of python but it didn't work after installed it.
