### ISSUE TITLE
"ZeroDivisionError: float division by zero" at startup, 2.75/2.76

### ISSUE THREAD

**Issue by rwaguy** [JacquesLucke/animation_nodes#273]
Just downloaded and installed via the addons menu, getting ""ZeroDivisionError: float division by zero" error on Blender startup.

The simple tutorials from BlenderDiplom don't work, nothing happens to objects, assuming it's disabled.  It remains checked in the addons menu, with no errors in Blender's "info" window.  Same issue in Blender 2.75/2.76, on Linux Mint 64-bit.

Thank you!

-----

~/Downloads/blender-2.75a-linux-glibc211-x86_64 $ ./blender
connect failed: No such file or directory
Read new prefs: /home/someguy/.config/blender/2.75/config/userpref.blend
found bundled python: /home/someguy/Downloads/blender-2.75a-linux-glibc211-x86_64/2.75/python
Registered Animation Nodes with 344 modules.
Traceback (most recent call last):
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/events.py", line 57, in fileLoaded
    file_tests.checkCurrentFile()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/file_tests.py", line 2, in checkCurrentFile
    updateSubprograms()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/file_tests.py", line 6, in updateSubprograms
    forceSubprogramUpdate()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/nodes/system/subprogram_sockets.py", line 13, in forceSubprogramUpdate
    _updateSubprogramInvokerNodes()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/nodes/system/subprogram_sockets.py", line 4, in _updateSubprogramInvokerNodes
    tree_info.updateIfNecessary()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/tree_info.py", line 337, in updateIfNecessary
    update()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/timing.py", line 13, in wrapper
    print("Time: {:.5f} - fps : {:.2f} - Function: {}".format(duration, 1 / duration, function.__name__))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/tree_info.py", line 447, in _updateTreeData
    update()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/timing.py", line 13, in wrapper
    print("Time: {:.5f} - fps : {:.2f} - Function: {}".format(duration, 1 / duration, function.__name__))
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/events.py", line 36, in sceneUpdated
    evaluateRaisedEvents()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/events.py", line 44, in evaluateRaisedEvents
    event_handler.update(event.getActives())
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/recursion.py", line 9, in wrapper
    result = function(*args, **kwargs)
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/event_handler.py", line 11, in update
    updateEverything()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/timing.py", line 10, in wrapper
    output = function(*args, **kwargs)
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/update.py", line 16, in updateEverything
    tree_info.update()
  File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/timing.py", line 13, in wrapper
    print("Time: {:.5f} - fps : {:.2f} - Function: {}".format(duration, 1 / duration, function.__name__))
ZeroDivisionError: float division by zero

**Comment by JacquesLucke** [comment]
This is a bug in my addon and should be reported here:
https://github.com/JacquesLucke/animation_nodes [2] 

I will fix this now, You can download a fixed Version in 5 min. 

Am 2015-10-19 12:55, schrieb rwaguy: 

> Just downloaded and installed via the addons menu, getting ""ZeroDivisionError: float division by zero" error on Blender startup. 
> 
> The simple tutorials from BlenderDiplom don't work, nothing happens to objects, assuming it's disabled. It remains checked in the addons menu, with no errors in Blender's "info" window. Same issue in Blender 2.75/2.76, on Linux Mint 64-bit. 
> 
> Thank you! 
> -------------------------
> 
> ~/Downloads/blender-2.75a-linux-glibc211-x86_64 $ ./blender
> connect failed: No such file or directory
> Read new prefs: /home/someguy/.config/blender/2.75/config/userpref.blend
> found bundled python: /home/someguy/Downloads/blender-2.75a-linux-glibc211-x86_64/2.75/python
> Registered Animation Nodes with 344 modules.
> Traceback (most recent call last):
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/events.py", line 57, in fileLoaded
> file_tests.checkCurrentFile()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/file_tests.py", line 2, in checkCurrentFile
> updateSubprograms()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/file_tests.py", line 6, in updateSubprograms
> forceSubprogramUpdate()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/nodes/system/subprogram_sockets.py", line 13, in forceSubprogramUpdate
> updateSubprogramInvokerNodes()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/nodes/system/subprogram_sockets.py", line 4, in updateSubprogramInvokerNodes
> tree_info.updateIfNecessary()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/tree_info.py", line 337, in updateIfNecessary
> update()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/timing.py", line 13, in wrapper
> print("Time: {:.5f} - fps : {:.2f} - Function: {}".format(duration, 1 / duration, function.__name))
> ZeroDivisionError: float division by zero
> Traceback (most recent call last):
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/tree_info.py", line 447, in updateTreeData
> update()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/timing.py", line 13, in wrapper
> print("Time: {:.5f} - fps : {:.2f} - Function: {}".format(duration, 1 / duration, function.__name_))
> ZeroDivisionError: float division by zero
> Traceback (most recent call last):
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/events.py", line 36, in sceneUpdated
> evaluateRaisedEvents()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/events.py", line 44, in evaluateRaisedEvents
> event_handler.update(event.getActives())
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/recursion.py", line 9, in wrapper
> result = function(_args, *_kwargs)
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/event_handler.py", line 11, in update
> updateEverything()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/timing.py", line 10, in wrapper
> output = function(_args, *_kwargs)
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/update.py", line 16, in updateEverything
> tree_info.update()
> File "/home/someguy/.config/blender/2.75/scripts/addons/animation_nodes-master/utils/timing.py", line 13, in wrapper
> print("Time: {:.5f} - fps : {:.2f} - Function: {}".format(duration, 1 / duration, function.NAME))
> ZeroDivisionError: float division by zero 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/JacquesLucke/animation_nodes/issues/273
[2] https://github.com/JacquesLucke/animation_nodes

**Comment by JacquesLucke** [comment]
Oh sry. My mails were a bit messed up. You did everything correctly!
The bug is fixed already
