### ISSUE TITLE
[false alert]Cannot activate addon.

### ISSUE THREAD

**Issue by Norrolith** [JacquesLucke/animation_nodes#281]
The first time I attempted to activate the addon, it gave me an error regarding Numpy

Traceback (most recent call last):
  File "/usr/share/blender/2.76/scripts/modules/addon_utils.py", line 324, in enable
    mod = __import__(module_name)
  File "/home/unwary/.config/blender/2.76/scripts/addons/animation_nodes-master/__init__.py", line 39, in <module>
    modules = developer_utils.setup_addon_modules(__path__, __name__, "bpy" in locals())
  File "/home/unwary/.config/blender/2.76/scripts/addons/animation_nodes-master/developer_utils.py", line 35, in setup_addon_modules
    modules = import_submodules(names)
  File "/home/unwary/.config/blender/2.76/scripts/addons/animation_nodes-master/developer_utils.py", line 27, in import_submodules
    modules.append(importlib.import_module("." + name, package_name))
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/unwary/.config/blender/2.76/scripts/addons/animation_nodes-master/algorithms/mesh_generation/from_splines.py", line 1, in <module>
    from ... data_structures.splines.bezier_spline import BezierSpline
  File "/home/unwary/.config/blender/2.76/scripts/addons/animation_nodes-master/data_structures/splines/bezier_spline.py", line 1, in <module>
    import numpy
ImportError: No module named 'numpy'

I tried again a bit later and it is now giving me a different error, this time about developer utils

Traceback (most recent call last):
  File "/usr/share/blender/2.76/scripts/modules/addon_utils.py", line 324, in enable
    mod = __import__(module_name)
  File "/home/unwary/.config/blender/2.76/scripts/addons/animation_nodes-master/__init__.py", line 38, in <module>
    from . import developer_utils
ImportError: cannot import name 'developer_utils'

This is in blender 2.76, no other addons enabled.

**Comment by Norrolith** [comment]
I have done some additional testing and have determined that the problem is on my end, something with the PPA I use for development builds. Please consider this closed.
