### ISSUE TITLE
Text output appears broken

### ISSUE THREAD

**Issue by raingloom** [JacquesLucke/animation_nodes#382]
I'm testing dynamic test objects and ran into a problem.

First the backtrace (there are several but this seems the most relevant):
```
Traceback (most recent call last):
  File "/home/raingloom/.config/blender/2.76/scripts/addons/animation_nodes/execution/code_generator.py", line 106, in getNodeExecutionLines
    taggedLines = node.getTaggedExecutionCodeLines()
  File "/home/raingloom/.config/blender/2.76/scripts/addons/animation_nodes/base_types/node.py", line 331, in getTaggedExecutionCodeLines
    code = toString(self.getExecutionCode())
  File "/home/raingloom/.config/blender/2.76/scripts/addons/animation_nodes/base_types/node.py", line 368, in toString
    code = list(code)
  File "/home/raingloom/.config/blender/2.76/scripts/addons/animation_nodes/nodes/text/text_object_output.py", line 72, in getExecutionCode
    if s["Font"].isUsed:                yield "    textObject.font = font"
KeyError: 'bpy_prop_collection[key]: key "Font" not found'
```

I'd look into it but atm I'm too tired to dig into a new codebase.

System: Arch Linux x64, latest Blender, AN versions tested: 1.0, 1.5, master

Node and scene setup:

A text object, ran through an instantiator node (fully copy, non-linked), the resulting list is then iterated. Each object is moved and their text data is set to be their index.

However, their text remain the same as the source's. Setting the source's text through a node, outside the loop, changes text for all instances.

**Comment by raingloom** [comment]
nevermind, turns out my brain was too low on HP to realize that those nodes need to be activated
