### ISSUE TITLE
Text -> Replicate causes a runtime error.

### ISSUE THREAD

**Issue by shhlife** [JacquesLucke/animation_nodes#637]
Trying to create a text->replicate node and I get this error:

Traceback (most recent call last):
  File "/Applications/Blender_builds/current/blender.app/Contents/Resources/2.78/scripts/startup/bl_operators/node.py", line 131, in invoke
    result = self.execute(context)
  File "/Applications/Blender_builds/current/blender.app/Contents/Resources/2.78/scripts/startup/bl_operators/node.py", line 122, in execute
    self.create_node(context)
  File "/Applications/Blender_builds/current/blender.app/Contents/Resources/2.78/scripts/startup/bl_operators/node.py", line 92, in create_node
    node = tree.nodes.new(type=node_type)
RuntimeError: Error: Node type an_ReplicateTextsNode undefined

location: <unknown location>:-1

**Comment by JacquesLucke** [comment]
in the Cython branch? That is my fault. thanks for the report, will fix it soon.

You should be able to inserr the node using the search box.

**Comment by shhlife** [comment]
Yep, in the Cython branch. 

Happy to be able to help out!  thanks Jacques! :)

**Comment by JacquesLucke** [comment]
fixed it, I'll upload a new build soon (although not too much changed after the conference...)
