### ISSUE TITLE
AN 1.7.3 cython for linux not working

### ISSUE THREAD

**Issue by Nikos-Prinios** [JacquesLucke/animation_nodes#665]
Traceback (most recent call last):
  File "/home/colonel/Applications/blender-2.78b-linux-glibc219-x86_64/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/home/colonel/.config/blender/2.78/scripts/addons/animation_nodes/__init__.py", line 105, in <module>
    raise Exception(message)

**Downloaded from Graphicall**
**System : Archlinux (Manjaro)**

**Comment by JacquesLucke** [comment]
is this the full error message?

Have you tried both linux builds that are available on grapphicall?
