### ISSUE TITLE
Adding 'Join mesh data list' node gives an error

### ISSUE THREAD

**Issue by lemonAcidjuice** [JacquesLucke/animation_nodes#687]
Hi, a little problem encountered:
'Join mesh data list' node gives an error when chosen from the add/mesh menu (the node is not added) but works well when accessed from the search function.
Version: Blender 2.78c, Windows 10, with AN Cython branch uploaded here http://graphicall.org/1202.

Here is the corresponding trace:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\startup\bl_operators\node.py", line 131, in invoke
    result = self.execute(context)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\startup\bl_operators\node.py", line 122, in execute
    self.create_node(context)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\startup\bl_operators\node.py", line 92, in create_node
    node = tree.nodes.new(type=node_type)
RuntimeError: Error: Node type an_JoinMeshDataList undefined

**Comment by JacquesLucke** [comment]
ah thanks for the report, will fix that.

**Comment by JacquesLucke** [comment]
fixed it, thanks again.
