### ISSUE TITLE
Interpolation from Curve Mapping node broken

### ISSUE THREAD

**Issue by piegamesde** [JacquesLucke/animation_nodes#717]
This node suddenly does not work anymore: The field with the interpolation GUI just does not exist anymore. When trying to load a file containing this node or trying to add it to the Node Tree, the console logs:

```
Traceback (most recent call last):
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\base_types\node.py", line 133, in draw_buttons
    self.draw(layout)
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\nodes\interpolation\from_curve_mapping.py", line 31, in draw
    layout.template_curve_mapping(self.curveNode, "mapping", type = "NONE")
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\nodes\interpolation\from_curve_mapping.py", line 115, in curveNode
    node = material.node_tree.nodes.get(getattr(self, '["curveNodeName"]', self.identifier))
AttributeError: 'NoneType' object has no attribute 'nodes'

location: <unknown location>:-1
```

When trying to execute the node tree containing such a node, it shows:

```
location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\operators\profiling.py", line 16, in execute
    result = self.getProfilingResult()
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\operators\profiling.py", line 32, in getProfilingResult
    self.executeFunction()
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\operators\profiling.py", line 37, in executeFunction
    execute_TreeExecutiong()
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\operators\profiling.py", line 54, in execute_TreeExecutiong
    bpy.context.space_data.edit_tree.execute()
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\base_types\node_tree.py", line 90, in execute
    self._execute()
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\base_types\node_tree.py", line 103, in _execute
    success = unit.execute()
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\execution\main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes-master.problems.ExecutionUnitNotSetup

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\base_types\node.py", line 133, in draw_buttons
    self.draw(layout)
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\nodes\interpolation\from_curve_mapping.py", line 31, in draw
    layout.template_curve_mapping(self.curveNode, "mapping", type = "NONE")
  File "C:\Users\%USERNAME%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\animation_nodes-master\nodes\interpolation\from_curve_mapping.py", line 115, in curveNode
    node = material.node_tree.nodes.get(getattr(self, '["curveNodeName"]', self.identifier))
AttributeError: 'NoneType' object has no attribute 'nodes'

location: <unknown location>:-1
```

This bug appeared after restarting Blender after the last Crash, until then it worked fine. In backup saves this does not work either, so normally it shouldn't be save file-related, but on the other hand, when opening the startup file, everything works fine again. When I append the node tree to the startup file, it does not work and I can't add any of this node without error. When I load the startup file, use that node (it works fine) and then append the node tree, the imported Interpolation from Curve Mapping nodes are broken, but adding new ones is fine.

**Comment by JacquesLucke** [comment]
thx for the report. Can you send me the .blend file?

**Comment by piegamesde** [comment]
How?

**Comment by JacquesLucke** [comment]
Sorry for the delay, I had not much time before..

I'm not quite sure what caused the problem in the first place but here is a way to fix it for your file (that hopefully works for you as well).

1. Open the network.blend file 
2. Go to the materials tab in the node editor.
3. Select the *Helper Material for Animation Nodes".
4. Activate "Use Nodes" for this material.
5. Save the file (preferably under a new name at first)
6. Close and reopen Blender and load the just saved file. It should work again.

If this does not work, let me know.

I'll investigate this further to make sure that it does not happen in the next release again.

**Comment by piegamesde** [comment]
I can't find the "Helper Material for Animation nodes". What do you mean with the "materials tab in the node editor"? If it is Add->Material, there isn't one. If it is the "Shader" icon where you edit the materials, I don't know either.

I use AN 1.6.0, hope it is the right one. I also use the Node Wrangler addon, could this make a difference?

**Comment by JacquesLucke** [comment]
![bildschirmfoto vom 2017-05-30 23-35-02](https://cloud.githubusercontent.com/assets/5881326/26606036/a2af9a7c-4590-11e7-8d59-4e3ad0e3c761.png)

Yes, I tested this with the AN 1.6
Oh and yeah, I actually ment the shader node tree type.

**Comment by piegamesde** [comment]
So yes, my file works again, thanks for that. Sadly, my interpolations are all reset, I'll have to redo them again.

What caused the issue in the end? Since its only going to be fixed in the next update, I'd like to know how to avoid it.

**Comment by JacquesLucke** [comment]
I don't really know, I've never seen this bug before so maybe Blender did something wrong when it crashed. The "Use Nodes" checkbox should be turned on, otherwise the the Interpolation from Curve Mapping node cannot work (I know this relation is strange, it works that way due to some limitations in Blender).
For some reason the checkbox was turned off and though the node did not work anymore. I can add better error handling for this case.

**Comment by piegamesde** [comment]
"Use nodes is checked", the curves are still reset. You also don't need to restart Blender to update, saving is enough.

This material has a lot of RGB curves nodes in it that seem to be linked to the Interpolation node. There are way more than I used the node originally and it slows down the entire file. Especially, my view Default.001 doesn't work anymore and I think its because of the material.

So I basically won't use this node anymore and all problems will be gone. Perhaps you can talk to the Blender developers so that the change it in a way do don't need any trickery anymore to achieve this node.

**Comment by JacquesLucke** [comment]
Well you should not use this material yourself. I would make it invisible to the user if it were possible.

Also it definitly should not slow down the scene.

The Blender devs are already working on making things like that easier (the problem is that I can't easily create my own curve mappings or color ramps or whatever).
