### ISSUE TITLE
macOS will not enable

### ISSUE THREAD

**Issue by anadin** [JacquesLucke/animation_nodes#735]
I've been through a number of troubleshooting steps (my 2.78 and 2.78.5's were quarantined) + double checked numpy/python etc.

Turned of AN 1.6, restarted, removed, then manually removed a left over folder from folders but still this happens when attempting to enable AN 2.

Traceback (most recent call last):
  File "/Applications/Blender2.78/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/Users/anadin/Library/Application Support/Blender/2.78/scripts/addons/AnimationNodes2/__init__.py", line 155, in <module>
    modules = import_modules.importAllSubmodules(__path__[0], __package__)
  File "/Users/anadin/Library/Application Support/Blender/2.78/scripts/addons/AnimationNodes2/import_modules.py", line 8, in importAllSubmodules
    module = importlib.import_module("." + name, packageName)
  File "/Applications/Blender2.78/blender.app/Contents/Resources/2.78/python/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/anadin/Library/Application Support/Blender/2.78/scripts/addons/AnimationNodes2/algorithms/hashing/__init__.py", line 2, in <module>
    from . utils import strToEnumItemID
  File "animation_nodes/algorithms/hashing/utils.pyx", line 1, in init animation_nodes.algorithms.hashing.utils (/Users/jasperge/dev/blender_addons/animation_nodes/animation_nodes/algorithms/hashing/utils.c:1004)
ImportError: No module named 'animation_nodes'

I can't follow the error into here (c file on your HD)
(/Users/jasperge/dev/blender_addons/animation_nodes/animation_nodes/algorithms/hashing/utils.c:1004)

**Comment by JacquesLucke** [comment]
Looks like you renamed the addon folder to "AnimationNodes2". The name has to be "animation_nodes", otherwise it does not work.

**Comment by anadin** [comment]
aha! so easy - thanks Jacques
