### ISSUE TITLE
AN 2.0 crash after scripts reloaded

### ISSUE THREAD

**Issue by allkhor** [JacquesLucke/animation_nodes#790]
OS: Linux x86_64, Ubuntu 16.04.3 LTS, **Blender 2.79**, **Animation Node 2.0.4**

Steps to reproduce:
1) Create any AN nodes
2) Press F8(reload scripts)
3) Blender raise exception  to console and AN stop working
```
Animation Nodes can't be reloaded.
Exception in module register(): '/home/user/.config/blender/2.79/scripts/addons/animation_nodes/__init__.py'
Traceback (most recent call last):
  File "/home/user/App/Blender/2.79/scripts/modules/addon_utils.py", line 350, in enable
    mod.register()
  File "/home/user/.config/blender/2.79/scripts/addons/animation_nodes/__init__.py", line 176, in register
    bpy.utils.register_module(__name__)
  File "/home/user/App/Blender/2.79/scripts/modules/bpy/utils/__init__.py", line 685, in register_module
    raise Exception("register_module(%r): defines no classes" % module)
Exception: register_module('animation_nodes'): defines no classes
gc.collect() -> 18602
search for unknown operator 'AN_OT_deactivate_auto_execution', 'AN_OT_deactivate_auto_execution'
search for unknown operator 'AN_OT_floating_node_settings_panel', 'AN_OT_floating_node_settings_panel'
search for unknown operator 'AN_OT_network_navigation', 'AN_OT_network_navigation'
search for unknown operator 'AN_OT_node_search', 'AN_OT_node_search'
search for unknown operator 'AN_OT_deactivate_auto_execution', 'AN_OT_deactivate_auto_execution'
search for unknown operator 'AN_OT_floating_node_settings_panel', 'AN_OT_floating_node_settings_panel'
search for unknown operator 'AN_OT_network_navigation', 'AN_OT_network_navigation'
search for unknown operator 'AN_OT_node_search', 'AN_OT_node_search'
```

**Comment by JacquesLucke** [comment]
Unfortunately Animation Nodes currently does not support reloading. 
This won't change most likely because compiled extension modules can't be reloaded.

It might be possible to make it so that AN does still work after trying to reload but that does not have high priority for me atm.

**Comment by allkhor** [comment]
Thanks for the fast response. 
It would be great if the documentation contained some notes about know limitations and issues.

Thanks for the good add-on.

**Comment by JacquesLucke** [comment]
True. So far only the code produces this small warning in the error message you posted: `Animation Nodes can't be reloaded.`
