### ISSUE TITLE
Not working with  2.78 or 2.79 Blender

### ISSUE THREAD

**Issue by CptnEclectic** [JacquesLucke/animation_nodes#798]
Hello Jacques,
I've tried installing the animation_nodes_v2_0_macos.zip and the animation_nodes-master.zip and when I try to enable it I get a popup window saying 
Report: Error 
A Traceback (most recent call last): 
File "/private/var/folders/kc/8_s4cjIj05xb8fgb51mrd94h0000gn/T/AppTranslocation/D6CEC94C-D92C-475E-ABDB-D806D11D7A49/d/blenderapp/Contents/Resources/2.79/scripts/modules/addon_utils.py", line 331, in enable mod = import (module_name) 
File "/Users/joeyburrow/Library/Application Support/Blender/2.79/scripts/addons/animation_nodes/ init .py", line 57, in <module> raise Exception(message) Exception: 
There are multiple versions of the Animation Nodes addon installed 
Please uninstall/remove all older versions of the addon

**Comment by JacquesLucke** [comment]
Go into this folder: `/Users/joeyburrow/Library/Application Support/Blender/2.79/scripts/addons/`
remove all folders that have have "animation nodes" in the name. Then install the mac version from the release page.

Maybe some directory in this path is hidden by default.

**Comment by CptnEclectic** [comment]
Thank you for the fix, working perfectly now!
