### ISSUE TITLE
Equalizer Demos not working anymore

### ISSUE THREAD

**Issue by gringlas** [JacquesLucke/animation_nodes#831]
Hi i'm using one of those nice equalizers from this video: https://www.youtube.com/watch?v=D-y8REUdg6I 
In Blender 2.78 they were working alright, but today I opened my project in 2.79a and it seems like if there are some nodes missing. 
I'm on Windows 10 (64bit) and Blender 2.79 and have installed Animation Nodes from https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0 
In the attached screenshot, you can see the node setup of " Linear Spline Tube.blend "from the files attached to the video mentioned above. 
![equalizer](https://user-images.githubusercontent.com/4557329/32994184-1d38332a-cd64-11e7-9b6c-d6fa9b46c546.JPG)
I also had a look into the System Console and it gave me those messages, when I opened Linear Spline Tube.blend. 
Thank you for reading!

```
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: C:\Program Files (x86)\Steam\steamapps\common\Blender\2.79\python
Read blend: C:\Users\seb\Dropbox\blenderprojects\Hendrik\VideoWithEqualizer\Linear Scale Equalizer.blend
Registered Animation Nodes with 497 modules.
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\handlers.py", line 45, in sceneUpdatePost
    handler(scene)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\events.py", line 36, in sceneUpdated
    evaluateRaisedEvents()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\events.py", line 44, in evaluateRaisedEvents
    event_handler.update(event.getActives())
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\event_handler.py", line 18, in update
    updateEverything()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\timing.py", line 13, in wrapper
    output = function(*args, **kwargs)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\update.py", line 17, in updateEverything
    tree_info.update()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\timing.py", line 13, in wrapper
    output = function(*args, **kwargs)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\__init__.py", line 22, in update
    _forestData.update()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\forest_data.py", line 27, in update
    self.insertNodeTrees()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\forest_data.py", line 33, in insertNodeTrees
    self.insertNodes(tree.nodes, tree.name)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\forest_data.py", line 72, in insertNodes
    dataTypeBySocket[socketID] = socket.dataType
AttributeError: 'NodeSocket' object has no attribute 'dataType'
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 158, in draw_buttons
    self.draw(layout)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 24, in draw
    if self.outputNode is None:
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 89, in outputNode
    return self.network.getGroupOutputNode()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 440, in network
    return getNetworkWithNode(self)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\__init__.py", line 254, in getNetworkWithNode
    return _networks.networkByNode[node.toID()]
KeyError: ('NodeTree', 'Group Input')

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 167, in draw_label
    return self.drawLabel()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\list\create_list.py", line 56, in drawLabel
    return "Create " + toListDataType(self.assignedType)
TypeError: Can't convert 'NoneType' object to str implicitly

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 158, in draw_buttons
    self.draw(layout)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 24, in draw
    if self.outputNode is None:
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 89, in outputNode
    return self.network.getGroupOutputNode()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 440, in network
    return getNetworkWithNode(self)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\__init__.py", line 254, in getNetworkWithNode
    return _networks.networkByNode[node.toID()]
KeyError: ('NodeTree', 'Group Input')

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 167, in draw_label
    return self.drawLabel()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\list\create_list.py", line 56, in drawLabel
    return "Create " + toListDataType(self.assignedType)
TypeError: Can't convert 'NoneType' object to str implicitly

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 158, in draw_buttons
    self.draw(layout)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 24, in draw
    if self.outputNode is None:
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 89, in outputNode
    return self.network.getGroupOutputNode()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 440, in network
    return getNetworkWithNode(self)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\__init__.py", line 254, in getNetworkWithNode
    return _networks.networkByNode[node.toID()]
KeyError: ('NodeTree', 'Group Input')

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 167, in draw_label
    return self.drawLabel()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\list\create_list.py", line 56, in drawLabel
    return "Create " + toListDataType(self.assignedType)
TypeError: Can't convert 'NoneType' object to str implicitly

location: <unknown location>:-1

location: <unknown location>:-1
trying to save userpref at C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend ok
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 158, in draw_buttons
    self.draw(layout)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 24, in draw
    if self.outputNode is None:
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 89, in outputNode
    return self.network.getGroupOutputNode()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 440, in network
    return getNetworkWithNode(self)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\__init__.py", line 254, in getNetworkWithNode
    return _networks.networkByNode[node.toID()]
KeyError: ('NodeTree', 'Group Input')

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 167, in draw_label
    return self.drawLabel()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\list\create_list.py", line 56, in drawLabel
    return "Create " + toListDataType(self.assignedType)
TypeError: Can't convert 'NoneType' object to str implicitly

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 158, in draw_buttons
    self.draw(layout)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 24, in draw
    if self.outputNode is None:
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\subprogram\group_input.py", line 89, in outputNode
    return self.network.getGroupOutputNode()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 440, in network
    return getNetworkWithNode(self)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\tree_info\__init__.py", line 254, in getNetworkWithNode
    return _networks.networkByNode[node.toID()]
KeyError: ('NodeTree', 'Group Input')

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\base_node.py", line 167, in draw_label
    return self.drawLabel()
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\list\create_list.py", line 56, in drawLabel
    return "Create " + toListDataType(self.assignedType)
TypeError: Can't convert 'NoneType' object to str implicitly

location: <unknown location>:-1

location: <unknown location>:-1
Read blend: C:\Users\seb\Downloads\Linear Move Equalizer.blend
WARNING: link removed
    Tree: 'NodeTree'
    From Socket: 'Evaluate Sound' -> 'strengths'
    To Socket: 'Invoke Subprogram.001' -> 'parameter.001'

Read blend: C:\Users\seb\Downloads\Linear Move Equalizer.blend
WARNING: link removed
    Tree: 'NodeTree'
    From Socket: 'Evaluate Sound' -> 'strengths'
    To Socket: 'Invoke Subprogram.001' -> 'parameter.001'

Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\handlers.py", line 42, in sceneUpdatePost
    @persistent
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\handlers.py", line 42, in sceneUpdatePost
    @persistent
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\handlers.py", line 42, in sceneUpdatePost
    @persistent
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\handlers.py", line 42, in sceneUpdatePost
    @persistent
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\utils\handlers.py", line 42, in sceneUpdatePost
    @persistent
KeyboardInterrupt
Read blend: C:\Users\seb\Downloads\Cube Array Equalizer.blend
WARNING: link removed
    Tree: 'NodeTree'
    From Socket: 'Evaluate Sound' -> 'strengths'
    To Socket: 'Invoke Subprogram' -> 'parameter_njkcz_input'

Read blend: C:\Users\seb\Downloads\Linear Spline Tube.blend
WARNING: socket removed
    Tree: 'NodeTree'
    Node: 'Curve Object Output.001'
    Name: 'Fill Mode'
WARNING: socket removed
    Tree: 'NodeTree'
    Node: 'Curve Object Output'
    Name: 'Fill Mode'
WARNING: link removed
    Tree: 'NodeTree'
    From Socket: 'Math.004' -> 'result'
    To Socket: 'Evaluate Sound.001' -> 'frame'

WARNING: link removed
    Tree: 'NodeTree'
    From Socket: 'Evaluate Sound.001' -> 'strength'
    To Socket: 'Math.003' -> 'a'

WARNING: link removed
    Tree: 'NodeTree'
    From Socket: 'Create List.002' -> 'outList'
    To Socket: 'Curve Object Output.001' -> 'splines'
```

**Comment by JacquesLucke** [comment]
Those node setups don't work in the newest version AN. Also there are better ways to archive the same results now.
Checkout the examples here: http://animation-nodes-manual.readthedocs.io/en/latest/release_notes/v2_0/sound.html
