### ISSUE TITLE
Set Vertex Color fails

### ISSUE THREAD

**Issue by Pred3d** [JacquesLucke/animation_nodes#834]
In this setup I get an error setting the Vertex Color

![set_vert_col](https://user-images.githubusercontent.com/15658640/33240539-928971ea-d2b7-11e7-9134-7353d1f02907.png)

Console log:

Traceback (most recent call last):
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 15, in <module>
  File "C:\Users\peter\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\nodes\color\set_vertex_color.py", line 53, in execute
    colorLayer.data.foreach_set("color", colors)
RuntimeError: internal error setting the array

**Comment by JacquesLucke** [comment]
does this happen when the cube is in another mode?

**Comment by Pred3d** [comment]
Same Problem with edit mode and vertex paint mode.

**Comment by JacquesLucke** [comment]
looks like Blender does not support this anymore.

Can you share the file?

**Comment by Pred3d** [comment]
Sorry, I messed up my Blender version. The current official AN 2.0 works perfectly with the official 2.79!
For testing purposes this is the file: http://pasteall.org/blend/index.php?id=48447
