### ISSUE TITLE
BUG: Adding "Mesh from Object" does not work

### ISSUE THREAD

**Issue by zuggamasta** [JacquesLucke/animation_nodes#897]
Trying to Add "Mesh from Object" on Mac OSX 10.11.6 results in this message.
AN 2.1 py_35 OSX
I had the same on my work machine with AN 2.1 py_25 OSX

```
Traceback (most recent call last):
  File "/Applications/Blender/blender.app/Contents/Resources/2.79/scripts/startup/bl_operators/node.py", line 131, in invoke
    result = self.execute(context)
  File "/Applications/Blender/blender.app/Contents/Resources/2.79/scripts/startup/bl_operators/node.py", line 122, in execute
    self.create_node(context)
  File "/Applications/Blender/blender.app/Contents/Resources/2.79/scripts/startup/bl_operators/node.py", line 92, in create_node
    node = tree.nodes.new(type=node_type)
RuntimeError: Error: Node type an_MeshFromObjectNode undefined


location: <unknown location>:-1


```

**Comment by JacquesLucke** [comment]
Thanks, the menu is fixed already. The fix will be available for everyons when I upload the next test builds.

For now just use the search to insert the Mesh Object Input node.
