### ISSUE TITLE
crash on windows with latest build python 3.6

### ISSUE THREAD

**Issue by mirlip** [JacquesLucke/animation_nodes#900]
When trying to open some files on windows, I get this error:
```
Traceback (most recent call last):
  File "C:\Users\test\Desktop\blender-2.79.0-git.f55adab-windows64\2.79\scripts\modules\addon_utils.py", line 338, in enable
    mod = __import__(module_name)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    modules = import_modules.importAllSubmodules(__path__[0], __package__)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\import_modules.py", line 8, in importAllSubmodules
    module = importlib.import_module("." + name, packageName)
  File "C:\Users\test\Desktop\blender-2.79.0-git.f55adab-windows64\2.79\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\base_types\nodes\vectorized_node.py", line 6, in <module>
    from .. effects import AutoSelectVectorization, VectorizeCodeEffect
ImportError: cannot import name 'AutoSelectVectorization'
```

**Comment by mirlip** [comment]
after a clean install it works. The crash was due to a new bug in Blender which has a fix pending.
