### ISSUE TITLE
Animation Nodes 2.1 failed

### ISSUE THREAD

**Issue by different55** [JacquesLucke/animation_nodes#909]
Upgrading to 2.1 beta gave me this error:

```
Traceback (most recent call last):
  File "/home/diff/.config/blender/2.79/scripts/addons/animation_nodes/__init__.py", line 140, in <module>
    try: from . import test_compile
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/Storage/SteamLibrary/steamapps/common/Blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/diff/.config/blender/2.79/scripts/addons/animation_nodes/__init__.py", line 158, in <module>
    raise Exception(message)
Exception: 

This build does not work at the moment.
  1. Check if the build you downloaded has been compiled for the OS
     you are using. If not, download another one.
  2. If you are on windows you can try to install a library called
     'Visual C++ 2015 Redistributable'. Should be easy to find using
     your search engine of choice.
  3. Try to use an official Blender release downloaded from blender.org.
  4. It is possible that you have a build for the correct platform
     but it still does not work. We experienced this mainly on linux.
     Try to find another build for your platform.
     If it still does not work, you have to compile AN yourself.
  5. Make a bug report on Github and give as much information
     as you can. Specifically the full error message, your OS, version, ...
```

OS is Solus 3.999

I downloaded the Python 3.5 version for Animation Nodes 3.1. The Python console in Blender says it's 3.5.3. Blender itself I get from Steam and is at version 2.79b. My system uses Python 3.6.4.

Tried making my own build but it builds for my system's version of python.

**Comment by Omeleto** [comment]
I have that same problem, and unfortunately that happens to me even I install it's previous release 2.0. Dunno why. I hope they respond.
