### ISSUE TITLE
Can't hide an object in Blender 2.8 (Mac)

### ISSUE THREAD

**Issue by dutzi** [JacquesLucke/animation_nodes#964]
In the following fairly simple graph, when clicking Toggle Viewport and Render Visibility I get the following error:

```
Traceback (most recent call last):
  File "/Users/eldad/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/operators/dynamic_operators.py", line 52, in invoke_InvokeFunction
    return self.execute(context)
  File "/Users/eldad/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/operators/dynamic_operators.py", line 58, in execute_InvokeFunction
    self.an_executeCallback(self.callback, *args)
  File "/Users/eldad/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/extend_bpy_types.py", line 28, in _executeCallback
    executeCallback(callback, *args, **kwargs)
  File "/Users/eldad/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/operators/callbacks.py", line 25, in executeCallback
    callback(*parameters, args, kwargs)
  File "/Users/eldad/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/operators/callbacks.py", line 48, in executeSocketCallback
    getattr(socket, functionName)(*args, **kwargs)
  File "/Users/eldad/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/sockets/object.py", line 67, in toggleObjectVisibilty
    object.hide_viewport = not object.hide_viewport
AttributeError: type object 'object' has no attribute 'hide_viewport'

location: <unknown location>:-1
```

![image](https://user-images.githubusercontent.com/927310/50070592-45134d00-01d7-11e9-926a-90b03f1fbae9.png)

**Comment by OmarSquircleArt** [comment]
Thanks for the report, that was already fixed.
