### ISSUE TITLE
Error enabling AN on Blender 2.8 (reports Shader issue)

### ISSUE THREAD

**Issue by bfontana** [JacquesLucke/animation_nodes#976]
Trying to enable AN on MacOS it throws error paste at end. I'm on High Sierra MacBook Pro Mid 2012, Basic Blender 2.8 works ok.

Error issued:

GPUShader: compile error:
ERROR: 0:72: Use of undeclared identifier 'gl_FragColor'

Traceback (most recent call last):
  File "/Users/bfontana/blender-2.80.0-git20181221.7a26e930a8c0-x86_64/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/bfontana/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/__init__.py", line 166, in <module>
    auto_load.init()
  File "/Users/bfontana/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/Users/bfontana/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/Users/bfontana/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/Users/bfontana/blender-2.80.0-git20181221.7a26e930a8c0-x86_64/blender.app/Contents/Resources/2.80/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/bfontana/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/nodes/viewer/viewer_3d.py", line 19, in <module>
    matricesShader = getShader(os.path.join(os.path.dirname(__file__), "matrix_shader.glsl"))
  File "/Users/bfontana/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/graphics/import_shader.py", line 10, in getShader
    return gpu.types.GPUShader("\n".join(lines[:i]), "\n".join(["\n"] * index + lines[i:]))
Exception: Shader Compile Error, see console for more details

**Comment by OmarSquircleArt** [comment]
See #961 .
