### ISSUE TITLE
Error on converting text to mesh with 'Separate Text Object' node.

### ISSUE THREAD

**Issue by AbhaySharma-tp** [JacquesLucke/animation_nodes#977]
Error on converting text to mesh While using the "Separate Text Object' node.

Traceback (most recent call last):
  File "F:\Blender_Versions\Blender_2.8\2.80\scripts\addons\animation_nodes\operators\dynamic_operators.py", line 52, in invoke_InvokeFunction
    return self.execute(context)
  File "F:\Blender_Versions\Blender_2.8\2.80\scripts\addons\animation_nodes\operators\dynamic_operators.py", line 58, in execute_InvokeFunction
    self.an_executeCallback(self.callback, *args)
  File "F:\Blender_Versions\Blender_2.8\2.80\scripts\addons\animation_nodes\extend_bpy_types.py", line 28, in _executeCallback
    executeCallback(callback, *args, **kwargs)
  File "F:\Blender_Versions\Blender_2.8\2.80\scripts\addons\animation_nodes\operators\callbacks.py", line 25, in executeCallback
    callback(*parameters, args, kwargs)
  File "F:\Blender_Versions\Blender_2.8\2.80\scripts\addons\animation_nodes\operators\callbacks.py", line 40, in executeNodeCallback
    getattr(node, functionName)(*args, **kwargs)
  File "F:\Blender_Versions\Blender_2.8\2.80\scripts\addons\animation_nodes\nodes\text\separate_text_object.py", line 95, in updateSeparation
    convertSelectedObjects(self.outputType)
  File "F:\Blender_Versions\Blender_2.8\2.80\scripts\addons\animation_nodes\nodes\text\separate_text_object.py", line 219, in convertSelectedObjects
    bpy.ops.object.convert(target = type)
  File "F:\Blender_Versions\Blender_2.8\2.80\scripts\modules\bpy\ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect

---------------------------------------

Also unable to render the file even if I turned on the "Lock Interface" in render menu.
here is the file:
https://drive.google.com/file/d/17N147G_ErUGE6ewGShNAoNZL8eGUKj2N/view?usp=sharing

**Comment by OmarSquircleArt** [comment]
Fixed in f69dda0.
